### ISSUE TITLE
Failed to resolve: com.smartlook.recording:app:1.5.2-native

### ISSUE THREAD

**Issue by goyalish** [smartlook/smartlook-mobile-issue-tracker#1]
**Platform**

Android
**Technology**

native
**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

com.smartlook.recording:app:1.5.2-native
**Summary**

Not able to download the dependency.
**Steps to reproduce [optional]**

add implementation('com.smartlook.recording:app:1.5.2-native') in the app build.gradle and sync
<img width="1440" alt="Screenshot 2020-08-26 at 3 33 40 PM" src="https://user-images.githubusercontent.com/13303203/91290668-8718d280-e7b1-11ea-9b88-52d3d02b405e.png">

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
Have you added:

```allprojects {
  repositories {
    maven {
      url "https://sdk.smartlook.com/android/release"
    }
  }
}
```
into project’s `build.gradle`?

**Comment by goyalish** [comment]
So silly of me.
Thanks for quick help. 
Now I am getting dependency resolution error.
Have you encountered following error earlier?
Duplicate class a.a.a.a.a found in modules jetified-app-1.5.2-native-runtime.jar (com.smartlook.recording:app:1.5.2-native) and jetified-engagement_rewards_1_1_0-runtime.jar (engagement_rewards_1_1_0.aar)

Go to the documentation to learn how to Fix dependency resolution errors.

**Comment by SenNeonoveNoci** [comment]
@goyalish We will look into this issue. Can you tell me more about `engagement_rewards_1_1_0.aar`?

**Comment by goyalish** [comment]
This is a third party sdk that our project has added and it is not hosted any where so we have added it in the libs folder only.
So I was wondering If I can do something like 
//smartlook
    implementation('com.smartlook.recording:app:1.5.2-native') {
        exclude group: "com.smartlook.recording", module: "jetified-app-1.5.2-native-runtime"
    }
to exclude it.

**Comment by goyalish** [comment]
Yes, Agree but unfortunately contacting engagement_rewards_1_1_0's team is not feasible. 
**We publish proguard settings bundled with our library, so we are compatible with other libraries.**
Can you share the pro-guard rules for your SDK? or any link will also be useful.

**Comment by ducbka02** [comment]
@SenNeonoveNoci Why you close this issue. I have the same problem when try use smartlook-react-native-wrapper
![image](https://user-images.githubusercontent.com/8655404/100308770-bff85b80-2fdb-11eb-90c8-5dddf9e3049e.png)
Have more conflict with this lib: 
https://github.com/stringeecom/stringee-react-native

**Comment by harshsidananykaa** [comment]
Hi @SenNeonoveNoci We are also facing the same issue while adding your dependency to our existing project.
``` Gradle 
Duplicate class a.a.a.a.a found in modules jetified-app-1.7.0-native-runtime.jar (com.smartlook.recording:app:1.7.0-native) and jetified-cashfreeSDK-1.5.3-runtime.jar (cashfreeSDK-1.5.3.aar)

```
Please can you provide me with the code which I can run to exclude `jetified-app-1.7.0-native-runtime.jar `
Currently I have tried 
```Gradle
implementation('com.smartlook.recording:app:1.7.0-native') {
exclude group: "com.smartlook.recording", module: "jetified-app-1.7.0-native-runtime"
}
```

**Comment by SebastianMieszczanczyk** [comment]
> Have you added:
> 
> ```
> allprojects {
>   repositories {
>     maven {
>       url "https://sdk.smartlook.com/android/release"
>     }
>   }
> }
> ```
> 
> into project’s `build.gradle`?

This is working solution for me

**Comment by SchneiderOr** [comment]
Any news about this one??
Im also getting the same error after upgrading to latest react-native SDK
it collides with https://github.com/transistorsoft/react-native-background-geolocation, how can i exclude it?

**Comment by Samuelungbede1** [comment]
<img width="962" alt="Screenshot 2022-03-02 at 17 21 49" src="https://user-images.githubusercontent.com/63721672/156403336-c167c01b-432a-4bfb-98b1-8efa3442137b.png">
I followed the smartLook docs, I still get this error
