### ISSUE TITLE
Sensitive data - How to bring view in front of black list views?

### ISSUE THREAD

**Issue by GTBulla** [smartlook/smartlook-mobile-issue-tracker#10]
**Platform**
Android

**Technology**
kotlin

**Smartlook SDK version**
1.3.0

**Summary**
I wants to know more how apply sensitive data.
My screen have float button and images with check buttons in recyclerview. 
I used Smartlook.registerBlacklistedView(thumbImageView) to hide sensitive data of image.
But the float button and check buttons are not visibles on record.
I tries to use properties translationZ and elevation and method bringToFront, but not working.
Help me please!

**Example Project [optional]**
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/thumbCardView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">

    <ImageView
        android:id="@+id/thumbImageView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        app:layout_constraintDimensionRatio="H,1:1"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"/>

    <CheckBox
        android:id="@+id/itemCheckBox"
        android:layout_gravity="bottom|right"
        android:layout_marginRight="@dimen/thumb_margin_checkbox"
        android:layout_marginBottom="@dimen/thumb_margin_checkbox"
        app:layout_constraintBottom_toBottomOf="@id/thumbImageView"
        app:layout_constraintRight_toRightOf="@id/thumbImageView"/>

</androidx.constraintlayout.widget.ConstraintLayout>

**Relevant logs and/or screenshots**
![image](https://user-images.githubusercontent.com/35339202/93515036-59313480-f8fe-11ea-96ce-d2429b751f77.png)
![image](https://user-images.githubusercontent.com/35339202/93515542-23d91680-f8ff-11ea-9fb1-c5af43be2a5d.png)

**Comment by SenNeonoveNoci** [comment]
@GTBulla Sadly our sensitive view hiding is not this advanced. We capture the whole screen and then overlay it. So the `zTranslation` or `elevation` do not help your case.

What you can do in these cases is to try out our `wireframe` rendering mode.
Just please update the SDK to `implementation 'com.smartlook.recording:app:1.5.3-native'`. And then follow the documentation on [rendering modes](https://smartlook.github.io/docs/sdk/api-reference?platform=android#rendering).

For the start, you can try:
```
Smartlook.setRenderingMode(RenderingMode.WIREFRAME);
```
