### ISSUE TITLE
Building iOS using Ionic/Cordova crashes due to "SmartLook/SmartLook.h" file not found.

### ISSUE THREAD

**Issue by cschratz** [smartlook/smartlook-mobile-issue-tracker#103]
**Platform**
iOS

**Technology**
Ionic Cordova

**Build instructions [optional]**
Running the "ionic cordova build ios" command

**Smartlook SDK version**
Ionic SDK

**Summary**
When running the command "ionic cordova build ios" the xcode build fails when it has to install the smartlook ios plugin. The error is as follows.

```
projectName/Plugins/cordova-plugin-smartlook/SmartlookPlugin.m:2:9: fatal error: Smartlook/Smartlook.h file not found
#import <Smartlook/Smartlook.h>
        ^~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Additional Information
Android builds just fine and is updating the dashboard with recordings. 

Here's the import statements at the top of SmartlookPlugin.m

```
#import "SmartlookPlugin.h"
#import <Smartlook/Smartlook.h>
#import <WebKit/WebKit.h>
```

**Comment by ramikhafagi96** [comment]
Any updates on this issue?
