### ISSUE TITLE
Ionic Cordova iOS videos not appearing in dashboard

### ISSUE THREAD

**Issue by cschratz** [smartlook/smartlook-mobile-issue-tracker#104]
**Platform**
iOS

**Technology**
Ionic 4 with Cordova

**Smartlook SDK version**
Ionic SDK ("@ionic-native/smartlook": "^5.36.0")

**Summary**
iOS recordings are not showing up in the dashboard, but Android are. No errors during the building process. But it seems as if the recordings are not properly being sent to the dashboard.

**Comment by vaclav-halik-smartlook** [comment]
Hi Connor, our SDK is currently unable to capture content from players implemented using the AVFoundation framework. This framework is implemented in a way that makes it impossible to access the presented video data. 

Obviously this is a long-standing architectural issue on Apple's part, as their own ReplayKit screen capture library cannot do this either. Apple itself points this out in the documentation.

We are currently unable to help you with this.
