### ISSUE TITLE
Smartlook is using a deprecated version of the Android Embedding [Flutter]

### ISSUE THREAD

**Issue by juanagu** [smartlook/smartlook-mobile-issue-tracker#105]
**Platform**
- Android

**Technology**
 - Flutter
 
**Smartlook SDK version**
2.0.1

**Summary**

```
The plugin `smartlook` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.
```

**Steps to reproduce [optional]**
Try to build an app for android using Flutter 2.5 and Android API 30.

**Comment by krystofcelba** [comment]
Hey @juanagu,
this is fixed in our latest release `v3.0.3`. Just be sure to change the package name to flutter_smartlook in your `pubspec.yaml` as we had to rename it. Here you can check the new package listing -> [flutter_smartlook](https://pub.dev/packages/flutter_smartlook).
