### ISSUE TITLE
Flutter web support

### ISSUE THREAD

**Issue by andre-paraense** [smartlook/smartlook-mobile-issue-tracker#107]
**Platform**
Web

**Technology**
Flutter

**Summary**
Flutter SDKs does not support web

Do you have any plans on supporting Flutter web anytime soon? This would be relevant for adoption, you already have a Flutter package that supports Android and iOS, so it would be just the case of extending it to support web as well.

**Comment by andre-paraense** [comment]
Awesome, we have been building our native apps and our web apps with Flutter, so having an unified solution would be great!

**Comment by pavel-kroh-smartlook** [comment]
Hi, we have passed the requirement to our colleagues in the product management. If you want to get in direct contact with them please contact us via `sales`. Thanks.
