### ISSUE TITLE
iOS Cordova plugin undeclared identifier errors

### ISSUE THREAD

**Issue by wsamoht** [smartlook/smartlook-mobile-issue-tracker#109]
**Platform**
- iOS (where errors exist)
- Android (working fine)

**Technology**
- Ionic 5
- Capacitor 3
- Xcode 12.4

**Packages used**
Please note that `@ionic-native` has been moved/renamed to `@awesome-cordova-plugins`.

```
npm install @awesome-cordova-plugins/smartlook // v5.37.0
npm install cordova-plugin-smartlook // v1.9.1
```

**Summary**
When trying to build my Ionic project in Xcode, it throws "Use of undeclared identifier" errors in `SmartlookPlugin.m` file.

This is happening within the `internalSetup` method where it is populating the `options` dictionary. It doesn't like the following variables:
- `SLSetupOptionUseAdaptiveFramerateKey`
- `SLSetupOptionFramerateKey`
- `SLSetupOptionRenderingModeKey`
- `SLSetupOptionStartNewSessionKey`
- `SLSetupOptionStartNewSessionKey`
- `SLSetupOptionStartNewSessionAndResetUserKey`

It is also throwing an error "No known class method" for this snippet:
```
[Smartlook setupWithKey:key options:options];
```

**Example Project**
Let me know if you would like me to provide an example Ionic project.

**Relevant logs and/or screenshots**

![screenshot_20211027200244](https://user-images.githubusercontent.com/5725966/139164236-2efb5347-1074-4a03-bdf4-fe00e9bf4a91.png)

**Comment by pavel-kroh-smartlook** [comment]
Hi @wsamoht , 

It may be that something is cached somewhere.

We will release new Cordova plugin version that uses up-to-date version of the native SDK soon.. then uninstalling the Cordova Smartlook plugin, all possibles caches cleanup, and its installing again hopefully solves the issue.

There is already a PR for it: https://github.com/smartlook/cordova-smartlook/pull/29

cc: @krystofcelba

**Comment by pavel-kroh-smartlook** [comment]
Hi @wsamoht , the fixed version of Smartlook Cordova plugin (v1.9.3) has been just released by @krystofcelba

**Comment by wsamoht** [comment]
Things are now working with v.1.9.3. Thank you for the help!

**Comment by pavel-kroh-smartlook** [comment]
Thank you for checking and confirming the fix works!
