### ISSUE TITLE
Videos not populating on the recordings dashboard

### ISSUE THREAD

**Issue by akhilmishra016** [smartlook/smartlook-mobile-issue-tracker#11]
**Platform**
<Android, iOS, React>

**Summary**
<Have integrated the SDK in our dev build to see the recordings but not able to get them on the dashboard>

**Relevant logs and/or screenshots**
<We are able to see that our sessions have been recorded. 
![image](https://user-images.githubusercontent.com/71759485/93993354-44e0b200-fdac-11ea-9617-75b595f77b39.png)

But are not able to access these videos. 
![image](https://user-images.githubusercontent.com/71759485/93993397-52963780-fdac-11ea-9d62-b4992a7b18fe.png)

**Comment by SenNeonoveNoci** [comment]
Hello @akhilmishra016, I have a few questions and requests:
- Are you recording on wifi or on mobile connection?
- Can you share a snippet of how you initialize the Smartlook SDK?

**Comment by akhilmishra016** [comment]
1. Wifi
2. class UCSharedApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        Smartlook.setupAndStartRecording("our_key")
    }
}

**Comment by SenNeonoveNoci** [comment]
@akhilmishra016 This is snipper for `Android`? From your issue, it is not clear if you are trying Smartlook SDK on native application (Android/iOS) or you have a `React Native` application. Can you clarify this?

**Comment by akhilmishra016** [comment]
Native application

**Comment by akhilmishra016** [comment]
Our 
app is a mix of react native and native. This snipped is for native only. We did not try to record the react native portion

**Comment by SenNeonoveNoci** [comment]
@akhilmishra016 Ok this is super strange. Let me follow up with some more questions:

- Is there any change that `smartlook.com` is blocked on your local network (wifi)?
- Are you experiencing any crash? 
- Do you see some unusual logs in `logcat`? 

Also please enable Smartlook logging like this:
```
Smartlook.setupAndStartRecording("our_key")
Smartlook.debugLoggingAspects(listOf(LogAspect.SDK_METHODS, LogAspect.REST, LogAspect.LIFECYCLE, LogAspect.VIDEO_CAPTURE))
```

And send us please the log from one run of your application (please use fresh installation). You can filter the log using `Smartlook` keyword. Thanks!

**Comment by akhilmishra016** [comment]
Can i add our Dev to this chat in anyway ?

**Comment by SenNeonoveNoci** [comment]
@akhilmishra016 If he has a Github account he is basically here. This is a public issue tracker.

**Comment by stopdrake** [comment]
Hey @akhilmishra016 Will take it from here. 
@SenNeonoveNoci Will share the logs with you in some time.

**Comment by SenNeonoveNoci** [comment]
Hi, @stopdrake were you able to obtain some logs?

**Comment by stopdrake** [comment]
Hey @SenNeonoveNoci . Got delayed a bit. Attaching the log file with smartlook grep.
I can consistently see this error being thrown

`09-28 14:02:32.729 10633 11421 D Smartlook_VIDEO_FRAME: Should capture new frame.
09-28 14:02:32.731 10633 11421 E Smartlook_d: Exception IllegalArgumentException thrown with message: width and height must be > 0
09-28 14:02:33.304 10633 11421 D Smartlook_VIDEO_FRAME: Should capture new frame.
09-28 14:02:33.307 10633 11421 E Smartlook_d: Exception IllegalArgumentException thrown with message: width and height must be > 0
09-28 14:02:33.718 10633 11421 D Smartlook_VIDEO_FRAME: Should capture new frame.
09-28 14:02:33.722 10633 11421 E Smartlook_d: Exception IllegalArgumentException thrown with message: width and height must be > 0
[smartlook.txt](https://github.com/smartlook/smartlook-mobile-issue-tracker/files/5290975/smartlook.txt)
`

**Comment by akhilmishra016** [comment]
@SenNeonoveNoci any luck in identifying the issue ?

**Comment by SenNeonoveNoci** [comment]
@stopdrake @akhilmishra016 What version of SDK are you using?

**Comment by stopdrake** [comment]
Hey @SenNeonoveNoci The version is 'com.smartlook.recording:app:1.5.3-native'

**Comment by akhilmishra016** [comment]
@SenNeonoveNoci Could you pls update on the issue pls ?

**Comment by SenNeonoveNoci** [comment]
@akhilmishra016 Im sorry for the delay, sadly I was sick last two weeks.

Please try out this build:
```
implementation 'com.smartlook.recording:app:1.6.0-native-video-debug'
```
And send us full `Smartlook` logs please. There is a problem with activity reference it seems, this should tell us if this is the case.

**Comment by SenNeonoveNoci** [comment]
Issue abandoned by creator.
