### ISSUE TITLE
React Native/Typescript - Incorrect types path

### ISSUE THREAD

**Issue by zhahaoyu** [smartlook/smartlook-mobile-issue-tracker#110]
**Platform**

React Native (ios/Android)
**Technology**

React Native

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

1.2.2

**Summary**

IDE is not able to identify the correct path. Looks like the type entry `index.ts` was moved from `lib/typescript/index.ts` to `lib/typescript/src/index.d.ts` but in package.json file, it has not been updated yet.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
Hello @zhahaoyu,

thanks for the report. We will look into this and keep you updated.

**Comment by krystofcelba** [comment]
Hey @zhahaoyu,
May I ask what package manager do you use in the affected project? The files in the `lib` directory are generated during the `prepare` step during the installation of `smartlook-react-native-wrapper` package.

**Comment by zhahaoyu** [comment]
Hi @krystofcelba it is yarn

**Comment by krystofcelba** [comment]
@zhahaoyu is it version 2?

**Comment by SenNeonoveNoci** [comment]
Closed due to no client response.
