### ISSUE TITLE
Unable to record AVPlayer inside UIScrollView

### ISSUE THREAD

**Issue by roimulia2** [smartlook/smartlook-mobile-issue-tracker#111]
Hey there,

Is there an issue recording AVPlayer if it's within a UIScrollView? 
I tried to make it slSensitive = false..

`       Smartlook.unregisterBlacklisted(object: self.cropViewController.scrollView)
        self.cropViewController.scrollView.slSensitive = false
`

Any other clue?

**Comment by SenNeonoveNoci** [comment]
@roimulia2 I guess `AVPlayer` is some kind of `Surface`, if you want to record `Surface` you need to enable `experimental` recording:
```
Smartlook.SetupOptionsBuilder builder = new Smartlook.SetupOptionsBuilder(API_KEY)
            .setExperimental(true);
```

These lines can be removed:
```
Smartlook.unregisterBlacklisted(object: self.cropViewController.scrollView) 
self.cropViewController.scrollView.slSensitive = false  
```

**Comment by pavel-kroh-smartlook** [comment]
Hi @roimulia2 , just to clarify, could you confirm:

1. It is an iOS issue, right?
2. what does it mean "Unable to record AVPlayer" - the recording is blank/black rectangle?

In short: on iOS, in some cases, the system prevents the app (i.e., the SDK in it, too) from capturing the image from the player. Thus, the recording is blank then.

**Comment by roimulia2** [comment]
Hey @SenNeonoveNoci , is this API supported in iOS as well? Can't find it

**Comment by roimulia2** [comment]
Hey @pavel-kroh-smartlook , yes it's on iOS. The recording is Blank. The weird part is that if I run it from Simulator the recordings of the AVPlayer works perfectly. If I'm doing it from device it's wont show anything (AVPlayer areas is blank)

**Comment by roimulia2** [comment]
Also important note, on a physical device, somewhere else in the app where the AVPlayer is not inside a UIScrollView, I can see the player recorded as expected

**Comment by pavel-kroh-smartlook** [comment]
Hi @roimulia2 ,

the cause of the issue is explained in details here: https://docs.smartlook.com/docs/sdk/cookbooks/ios-avplayer-recording?platform=ios

On physical device, it is impossible to record the AVPlayer due to technical constraints on the iOS side. It has nothing to do with Smartlook sensitivity handling. 

It works on simulator, because there the player video engine and GPU is simulated by macOS which allows it.

**Comment by roimulia2** [comment]
Thanks for the info! Appreciate it
