### ISSUE TITLE
Crash reported by Crashlytics related to Smartlook (AVAssetWriterInput)

### ISSUE THREAD

**Issue by LucasCoelho** [smartlook/smartlook-mobile-issue-tracker#112]
**Platform**
iOS

**Technology**
SwiftUI

**Build instructions [optional]**
n/a

**Rendering [optional]**
n/a

**Affected devices [optional]**
n/a

**Smartlook SDK version**
1.0.0

**Summary**
I integrated the SDK. Videos are being recorded but Crashlytics reports crashes related to Smartlool

**Steps to reproduce [optional]**
n/a

**Example Project [optional]**
n/a

**Relevant logs and/or screenshots**
1) 

Fatal Exception: NSInternalInconsistencyException
*** -[AVAssetWriterInput pixelBufferPool] A pixel buffer pool cannot be created with the receiver's sourcePixelBufferAttributes. The pixel buffer attributes must specify a width, height, and either a pixel format or a pixel format description.
_hidden#8400_
Crashed: com.google.firebase.crashlytics.ios.exception
SIGABRT ABORT 0x00000001ba0d99c4

Stack trace
```
Crashed: com.google.firebase.crashlytics.ios.exception
0  Ausum                          0xdad88 FIRCLSProcessRecordAllThreads + 397 (FIRCLSProcess.c:397)
1  Ausum                          0xdb168 FIRCLSProcessRecordAllThreads + 428 (FIRCLSProcess.c:428)
2  Ausum                          0xe706c FIRCLSHandler + 34 (FIRCLSHandler.m:34)
3  Ausum                          0xe6ea4 __FIRCLSExceptionRecord_block_invoke + 218 (FIRCLSException.mm:218)
4  libdispatch.dylib              0x3950 _dispatch_client_callout + 20
5  libdispatch.dylib              0x12a70 _dispatch_lane_barrier_sync_invoke_and_complete + 56
6  Ausum                          0xe6660 FIRCLSExceptionRecord + 225 (FIRCLSException.mm:225)
7  Ausum                          0xe694c FIRCLSExceptionRecordNSException + 111 (FIRCLSException.mm:111)
8  Ausum                          0xe6244 FIRCLSTerminateHandler() + 279 (FIRCLSException.mm:279)
9  libc++abi.dylib                0x12f58 std::__terminate(void (*)()) + 20
10 libc++abi.dylib                0x12ef4 std::terminate() + 64
11 libobjc.A.dylib                0x2a4d4 objc::DenseMapBase<objc::DenseMap<objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >, objc_class*, PendingInitialize*, objc::DenseMapValueInfo<PendingInitialize*>, objc::DenseMapInfo<objc_class*>, objc::detail::DenseMapPair<objc_class*, PendingInitialize*> >::FatalCorruptHashTables(objc::detail::DenseMapPair<objc_class*, PendingInitialize*> const*, unsigned int) const + 14
12 libdispatch.dylib              0x3964 _dispatch_client_callout + 40
13 libdispatch.dylib              0x6e04 _dispatch_continuation_pop + 504
14 libdispatch.dylib              0x64f8 _dispatch_async_redirect_invoke + 748
15 libdispatch.dylib              0x14f48 _dispatch_root_queue_drain + 388
16 libdispatch.dylib              0x15768 _dispatch_worker_thread2 + 164
17 libsystem_pthread.dylib        0x1174 _pthread_wqthread + 228
18 libsystem_pthread.dylib        0xf50 start_wqthread + 8
```

2)
Crashed: com.apple.NSURLSession-delegate
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

```
Crashed: com.apple.NSURLSession-delegate
0  Smartlook                      0x56990 _hidden#2172_ + 320284 (__hidden#923_:320284)
1  Smartlook                      0x568bc _hidden#7222_ + 320072 (__hidden#923_:320072)
2  Smartlook                      0x55fc0 Smartlook.urlSession(_:task:didCompleteWithError:) + 317772 (__hidden#923_:317772)
3  Smartlook                      0x5606c _hidden#7217_ + 317944 (__hidden#923_:317944)
4  CFNetwork                      0x1c5dc CFURLRequestCopyHTTPRequestMethod + 2396
5  libdispatch.dylib              0x1c04 _dispatch_call_block_and_release + 32
6  libdispatch.dylib              0x3950 _dispatch_client_callout + 20
7  libdispatch.dylib              0xb0ac _dispatch_lane_serial_drain + 664
8  libdispatch.dylib              0xbc44 _dispatch_lane_invoke + 444
9  libdispatch.dylib              0x16318 _dispatch_workloop_worker_thread + 656
10 libsystem_pthread.dylib        0x11b0 _pthread_wqthread + 288
11 libsystem_pthread.dylib        0xf50 start_wqthread + 8
```

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , 

thanks for the detailed report. 

Do you know on which device (model) this crash occurs? Is it a singular error, or does it repeat on different devices?

**Comment by pavel-kroh-smartlook** [comment]
Also, the Smartlook version is for sure not 1.0.0 which is 2 years old.

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho ,

thanks for the detailed report.

Do you know on which device (model) this crash occurs, which iOS version? Is it a singular error, or does it repeat on different devices?

Also, the Smartlook version is for sure not 1.0.0 which is 2 years old.

It would really help if you could share the full crashreport with us. If you don't want sharing it publicly, you could send it to my work email `pavelkroh@smartlook.com`.

**Comment by LucasCoelho** [comment]
Sorry, Smartlook 1.8.0
Sending you an email

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho ,

although we are unable to reproduce the crashes we found a faulty logic in our video writer handling, which under some circumstances might cause he first crash. 

The fix is on the way.

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , the new version (1.8.1) is released.

Among else, it fixes the business logic issue in video handling that probably caused the more frequent crash.

As for the other crash (in URLSession delegate method), we still investigate it.

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , there is new SDK version 1.8.3 released, it fixes several issue, among them the one you reported.

**Comment by LucasCoelho** [comment]
@pavel-kroh-smartlook are users are still having crashes related to Smartlook 1.8.3. Can I reopen the ticket somehow?
Thanks

**Comment by vaclav-halik-smartlook** [comment]
Hi @LucasCoelho, can I ask for details?

**Comment by LucasCoelho** [comment]
Here's the stack trace of one of the crashes:

Crashed: com.apple.NSURLSession-delegate
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
```
0  Smartlook                      0x5ddec _hidden#7457_ + 346796 (__hidden#1169_:346796)
1  Smartlook                      0x5cce0 _hidden#7446_ + 342432 (__hidden#946_:342432)
2  CFNetwork                      0x1bb64 CFURLRequestCopyHTTPRequestMethod + 2396
3  libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
5  libdispatch.dylib              0xbdf4 _dispatch_lane_serial_drain + 672
6  libdispatch.dylib              0xc99c _dispatch_lane_invoke + 444
7  libdispatch.dylib              0x171b8 _dispatch_workloop_worker_thread + 656
8  libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
9  libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

com.smartlook.sdk.CoreDataQueue (QOS: UTILITY)
```
0  CoreData                       0x2e7470 __49-[PFUbiquityContainerMonitor scheduleCheckBlock:]_block_invoke + 6581408880
1  CoreData                       0x20314 -[NSManagedObjectContext performBlockAndWait:] + 264
2  Smartlook                      0x7ecd4 _hidden#1539_ + 34 (__hidden#10352_:34)
3  Smartlook                      0x1782c _hidden#1993_ + 158 (__hidden#2031_:158)
4  Smartlook                      0x178ac _hidden#1994_ + 58732 (__hidden#946_:58732)
5  Foundation                     0x4fcac __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 24
6  Foundation                     0x5dd50 __NSOQSchedule_f + 184
7  libdispatch.dylib              0x2924 _dispatch_call_block_and_release + 32
8  libdispatch.dylib              0x4670 _dispatch_client_callout + 20
9  libdispatch.dylib              0x7b44 _dispatch_continuation_pop + 504
10 libdispatch.dylib              0x71a0 _dispatch_async_redirect_invoke + 596
11 libdispatch.dylib              0x15de0 _dispatch_root_queue_drain + 396
12 libdispatch.dylib              0x16608 _dispatch_worker_thread2 + 164
13 libsystem_pthread.dylib        0x10b8 _pthread_wqthread + 228
14 libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

com.apple.main-thread
mach_msg_trap
com.apple.uikit.eventfetch-thread
mach_msg_trap
com.google.firebase.crashlytics.MachExceptionServer
FIRCLSProcessRecordAllThreads
com.apple.NSURLConnectionLoader
mach_msg_trap
AVAudioSession Notify Thread
mach_msg_trap
com.apple.coreaudio.AQClient
mach_msg_trap
Thread #1
start_wqthread
Thread #2
start_wqthread

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho 

new SDK version has been released. 

It is a maintenance release that also aims to solve some of the crashed. Given the fact that there are ongoing issues with the crashes symbolication, we cannot guarantee we addressed all the crashes, however, we identified some patterns in them and fixed their causes.

New release version is 1.8.4, and it is available via [Swift Package Manager](https://github.com/smartlook/SmartlookSwiftPackage), Cocoapods (`pod Smartlook`) and for [direct download](https://sdk.smartlook.com/ios/smartlook-ios-sdk-1.8.4.52.zip).

**Comment by Kondamon** [comment]
To resolve missing (hidden) symbolications in the crash reports, please [see this comment](https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/128#issuecomment-1021201305).

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho ,

New Smartlook release 1.8.5 has been released. 

The release is dedicated mainly to bugfixing (it attempts to address all known bugs) and other maintenance.

Please give it a try when suitable.

Thanks for the patience.
