### ISSUE TITLE
White recordings for Flutter Web

### ISSUE THREAD

**Issue by ismadev** [smartlook/smartlook-mobile-issue-tracker#117]
Just appears a label that says: "Iframe is not recorded"

**Comment by pavel-kroh-smartlook** [comment]
Could you please provide more details?

Do you have a web generated by Flutter, or a native app created by Flutter presenting a Web view?

**Comment by ismadev** [comment]
> Could you please provide more details?
> 
> Do you have a web generated by Flutter, or a native app created by Flutter presenting a Web view?

I have copied the example at: https://pub.dev/packages/flutter_smartlook/example
I changed just the ApiKey
I installed SmartLook via Tag Manager
and deployed the site:
flutter build web --web-renderer canvaskit --release
firebase deploy --only hosting:MYWEBSITE

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, 2.6.0-12.0.pre.238, on Microsoft Windows [VersiÃ³n 10.0.19043.1348], locale es-ES)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 3.3)
[√] VS Code (version 1.62.2)
[√] Connected device (2 available)

• No issues found!

**Comment by pavel-kroh-smartlook** [comment]
Thanks for the details, I'll pass the issue now to my colleague who does the Flutter plugin. There is a state holiday here today, so he will get back to you later this week.

**Comment by ismadev** [comment]
> Thanks for the details, I'll pass the issue now to my colleague who does the Flutter plugin. There is a state holiday here today, so he will get back to you later this week.

thanks! :) just one question. SmartLook should work on flutter web applications? or just on flutter android/ios apps?

**Comment by pavel-kroh-smartlook** [comment]
Smartlook Flutter plugin is not supposed to work with web apps, the plugin contains the native Android and iOS SDKs only, and because the web draws on canvas, adding the web SDK would not be straightforward. We discuss adding this feature, but without any concrete plans or schedule.

The native SDKs can record content of embedded web views, though.

PS: Where did you see the `Iframe is not recorded` message? Did something record to our backend and is visible in the dashboard?

**Comment by ismadev** [comment]
![image](https://user-images.githubusercontent.com/2325441/142195484-073dbe0a-24d9-404b-af68-a9a6fb773611.png)

**Comment by pavel-kroh-smartlook** [comment]
I see. Unfortunately without support of my "flutter" colleagues, I cannot help at the moment. We will discuss it tomorrow here and let you know if there is a way how to make Smartlook working with Flutter Web. Thanks for your patience.

**Comment by ismadev** [comment]
> I see. Unfortunately without support of my "flutter" colleagues, I cannot help at the moment. We will discuss it tomorrow here and let you know if there is a way how to make Smartlook working with Flutter Web. Thanks for your patience.

thank you! any workaround is welcome :)

**Comment by pavel-kroh-smartlook** [comment]
Hi @ismadev ,

so it is clear now. 

1. The Smartlook Flutter Plugin works for generated mobile applications ony (iOS, Android). When generating a web, installing the plugin is not necessary.
2. The web application is recorded by Web SDK added by Tag Manager.
3. Flutter Web App however is not a classic Web app (with HTML UI), the UI is drawn in Canvas - which recording is not supported by Smartlook at this moment
4. Although Smartlook plans Canvas support in some future, no ETA is set.
5. There is unfortunately no workaround to record Canvas-based web apps by Smartlook now.

I've communicated your issue to our business team so they are aware about requests for canvas recording. You can also contact them on `sales@smartlook.com`.
