### ISSUE TITLE
App Crash just Start Smartlook SDK

### ISSUE THREAD

**Issue by kimtammu** [smartlook/smartlook-mobile-issue-tracker#118]
**Platform**
iOS

**Technology**
Native

**Affected devices [optional]**
Device running iOS 14

**Smartlook SDK version**
Smartlook SDK 1.8.1

**Summary**
App just start Smartlook , it will crash. 

**Relevant logs and/or screenshots**
Attach are crash lo
[Smartlook_CrashLog.zip](https://github.com/smartlook/smartlook-mobile-issue-tracker/files/7559390/Smartlook_CrashLog.zip)
g.

**Comment by pavel-kroh-smartlook** [comment]
Hi @kimtammu ,

thanks for the crash logs, they helped a lot to find the exact location of the crash.

Technically, the crash happens when Smartlook accesses a `CALayer` `presentation()` method.

This happens e.g.,  when there is an incorrectly defined animation on the `CALayer` instance, which sadly is also the case of some system frameworks.

Could you let us know what frameworks and UI components do you use at the start of the app? Something related to `AVPlayer` by a chance?

**Comment by kimtammu** [comment]
Hi @pavel-kroh-smartlook ,

Thank you for your reply. We are using SwiftUI framework and we found that LPLinkView may be the cause of App crash.  We remove the LPLinkView Component in the app and we can not detect any crash as before.

As we know that LPLinkView presents images , inline audio and video playback. This may something related to the AVPlayer framework that you suggest. Please help to check this.

Apple Documentation on LPLinkView
https://developer.apple.com/documentation/linkpresentation/lplinkview

**Comment by pavel-kroh-smartlook** [comment]
Hi @kimtammu , 

thank you a lot for additional details. 

Now we will probably be able to work it on in few days and release a fixed version then. 

Thanks again!

**Comment by pavel-kroh-smartlook** [comment]
Hi @kimtammu ,

we are able to reproduce a bit random crashes in Link Presentation framework. Workaround in on the way into the next release.

**Comment by pavel-kroh-smartlook** [comment]
Hi @kimtammu , we have just released new version where the issue with Link Presentation is fixed.

**Comment by kimtammu** [comment]
Hi @pavel-kroh-smartlook ,

We tested the Smartlook SDK iOS Version 1.8.2. We can not find the App crash related to Link Presentation framework again. The problem is solved.
 
Thank you for your work.

Kim

**Comment by pavel-kroh-smartlook** [comment]
Hi @kimtammu ,

thank you for your cooperation and patience,

Pavel
