### ISSUE TITLE
Proguard enabled means NO Recording

### ISSUE THREAD

**Issue by jiurchuk** [smartlook/smartlook-mobile-issue-tracker#12]
**Platform**
Android

**Technology**
Java + Kotlin

**Smartlook SDK version**
1.5.2

**Summary**
Smartlook doesn't record if `minifyEnabled` is `true`. (On `build.gradle` file)

**Steps to reproduce [optional]**
- Integrate Smartlook in your app
- Disable proguard minification and then the recording appears on the dashboard.
- Enable proguard minification and then Smartlook does not record at all.

Can you share your proguard rules?

**Comment by SenNeonoveNoci** [comment]
Client-specific issue handled on Discord.
