### ISSUE TITLE
About the render mode change

### ISSUE THREAD

**Issue by mericgerceker** [smartlook/smartlook-mobile-issue-tracker#125]
**Platform**
Android & iOS

**Technology**
Flutter 2.5.3

**Build instructions [optional]**
flutter_smartlook: ^3.0.5

**Affected devices [optional]**
Android Emulator or iOS Simulator

**Smartlook SDK version**
flutter_smartlook: ^3.0.5

**Summary**
Hi, when I change the render mode, "only POWER users can change the render mode!" I'm getting the answer. What is meant by "Power users" here? What method would you advice to hide sensitive data from some input on the screen?

**Relevant logs and/or screenshots**
`W/Smartlook_ConfigurationHandlerPreferencesBase(19125): setRenderingMethod(): only POWER users can change rendering mode!, [logAspect: MANDATORY]`

**Comment by SenNeonoveNoci** [comment]
Hello @mericgerceker,

rendering mode can be changed only if you have bought a "business" (or higher) Smartlook package. You can read more [here](https://www.smartlook.com/pricing/). 

Sorry for the misleading error name, the package was formerly called "power".

František Spurný
Android developer
