### ISSUE TITLE
Crash when endEditing view on iOS 1.8.3 version

### ISSUE THREAD

**Issue by aetxenike-sh** [smartlook/smartlook-mobile-issue-tracker#126]
**Platform**
iOS

**Technology**
Native

**Build instructions [optional]**
Swift Package Manager

**Smartlook SDK version**
1.8.3

**Summary**
The app crashes when trying to execute **[self.view endEditing:YES];**

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**
`Smartlook`____swizzle_target_action_block_invoke_2:
    0x10cb7b4d8 <+0>:   stp    x22, x21, [sp, #-0x30]!
    0x10cb7b4dc <+4>:   stp    x20, x19, [sp, #0x10]
    0x10cb7b4e0 <+8>:   stp    x29, x30, [sp, #0x20]
    0x10cb7b4e4 <+12>:  add    x29, sp, #0x20            ; =0x20 
    0x10cb7b4e8 <+16>:  mov    x20, x2
    0x10cb7b4ec <+20>:  mov    x21, x0
    0x10cb7b4f0 <+24>:  mov    x0, x1
    0x10cb7b4f4 <+28>:  bl     0x10cc5e5cc               ; symbol stub for: objc_retain
    0x10cb7b4f8 <+32>:  mov    x19, x0
    0x10cb7b4fc <+36>:  mov    x0, x20
    0x10cb7b500 <+40>:  bl     0x10cc5e5cc               ; symbol stub for: objc_retain
->  0x10cb7b504 <+44>:  mov    x20, x0
    0x10cb7b508 <+48>:  cbz    x19, 0x10cb7b580          ; <+168> at SLSwizzling+UIBarButtonItem.m:121:13
    0x10cb7b50c <+52>:  mov    x0, x19
    0x10cb7b510 <+56>:  bl     0x10cb7b9f4               ; sl_is_inside_swizzle at SwizzlingUtils.m:95
    0x10cb7b514 <+60>:  mov    x22, x0
    0x10cb7b518 <+64>:  tbnz   w0, #0x0, 0x10cb7b524     ; <+76> at SLSwizzling+UIBarButtonItem.m:115:39
    0x10cb7b51c <+68>:  mov    x0, x19
    0x10cb7b520 <+72>:  bl     0x10cb7ba40               ; sl_set_inside_swizzle at SwizzlingUtils.m:99
    0x10cb7b524 <+76>:  ldp    x8, x1, [x21, #0x20]
    0x10cb7b528 <+80>:  mov    x0, x19
    0x10cb7b52c <+84>:  mov    x2, x20
    0x10cb7b530 <+88>:  blr    x8
    0x10cb7b534 <+92>:  tbnz   w22, #0x0, 0x10cb7b580    ; <+168> at SLSwizzling+UIBarButtonItem.m:121:13
    0x10cb7b538 <+96>:  adrp   x8, 295
    0x10cb7b53c <+100>: ldr    x22, [x8, #0xb60]
    0x10cb7b540 <+104>: ldr    x0, [x21, #0x28]
    0x10cb7b544 <+108>: bl     0x10cc5e3a4               ; symbol stub for: NSStringFromSelector
    0x10cb7b548 <+112>: mov    x29, x29
    0x10cb7b54c <+116>: bl     0x10cc5e5e4               ; symbol stub for: objc_retainAutoreleasedReturnValue
    0x10cb7b550 <+120>: mov    x21, x0
    0x10cb7b554 <+124>: adrp   x8, 294
    0x10cb7b558 <+128>: ldr    x1, [x8, #0xf20]
    0x10cb7b55c <+132>: mov    x0, x22
    0x10cb7b560 <+136>: mov    x2, x21
    0x10cb7b564 <+140>: mov    x3, x20
    0x10cb7b568 <+144>: mov    x4, x19
    0x10cb7b56c <+148>: bl     0x10cc5e5a8               ; symbol stub for: objc_msgSend
    0x10cb7b570 <+152>: mov    x0, x21
    0x10cb7b574 <+156>: bl     0x10cc5e5c0               ; symbol stub for: objc_release
    0x10cb7b578 <+160>: mov    x0, x19
    0x10cb7b57c <+164>: bl     0x10cb7bab8               ; sl_reset_inside_swizzle at SwizzlingUtils.m:104:5
    0x10cb7b580 <+168>: mov    x0, x20
    0x10cb7b584 <+172>: bl     0x10cc5e5c0               ; symbol stub for: objc_release
    0x10cb7b588 <+176>: mov    x0, x19
    0x10cb7b58c <+180>: ldp    x29, x30, [sp, #0x20]
    0x10cb7b590 <+184>: ldp    x20, x19, [sp, #0x10]
    0x10cb7b594 <+188>: ldp    x22, x21, [sp], #0x30
    0x10cb7b598 <+192>: b      0x10cc5e5c0               ; symbol stub for: objc_release`

**Comment by pavel-kroh-smartlook** [comment]
Hi @aetxenike-sh , 

thanks for the detailed report. We will look into it and hopefully fix it in the upcoming maintenance release later in January.

**Comment by pavel-kroh-smartlook** [comment]
Hi @aetxenike-sh , it seems that the crash is related to using `UIBarButtonItem`. Is the `[self.view endEditing:YES]` called from a button action? If yes, could you please share the code (signature of) of the method linked to the button action or describe how the action is invoked? Thanks.

**Comment by aetxenike-sh** [comment]
It crashes when I execute endEditing in a UIView.

**Comment by pavel-kroh-smartlook** [comment]
Hi @aetxenike-sh , 

we cannot reproduce the issue. 

A call to `[self.view endEditing:YES];` does not itself crash an app. The stacktrace points to our methods that handle `UIBarButton` events, but testing them with different setups also works for us.

Do you know the exact exception that caused the crash? Was it `EXC_BAD_ACCESS` or something else?

**Comment by pavel-kroh-smartlook** [comment]
Hi @aetxenike-sh 

New Smartlook release 1.8.5 has been released. 

The release is dedicated mainly to bugfixing (it attempts to address all known bugs) and other maintenance.

Please give it a try when suitable.

Thanks for the patience.
