### ISSUE TITLE
TextInput is not being whitelisted on iOS using SmartLookSensitiveComponent

### ISSUE THREAD

**Issue by usamaimam1** [smartlook/smartlook-mobile-issue-tracker#129]
**Platform**
iOS

**Technology**
React Native

**Build instructions [optional]**
react-native: 0.64.0

**Rendering [optional]**

**Affected devices [optional]**
iOS devices
**Smartlook SDK version**
smartlook-react-native-wrapper: "^1.2.2",

**Summary**
I am using a reusable AppInput component across my app. And for that, I am using SmartLookSensitiveComponent declaratively to wrap my TextInput base component, and if valueType is username or email I set the isSensitive boolean to false. I want to see what email and usernames users type and any issues that they face at login. But on the dashboard Input fields are whitelisted and show in video recordings only on Android devices and on iOS inputs are still covered.

**Steps to reproduce [optional]**
No
**Example Project [optional]**
``` 
export default function AppInput({
  secureTextEntry,
  containerStyle,
  valueType,
  ...props
}) {
  const [isShown, setIsShown] = useState(false);
  const isAppInputSensitive =
    valueType === 'username' || valueType === 'email' ? false : true;
  return (
    <View style={[styles.container, containerStyle]}>
      <SmartlookSensitiveComponent isSensitive={isAppInputSensitive}>
        <TextInput
          style={styles.input}
          ref={ref =>
            ref &&
            ref.props &&
            ref.setNativeProps({
              text: ref.props.value,
              style: {...typography.bodyS, ...styles.input},
            })
          }
          secureTextEntry={secureTextEntry && !isShown}
          allowFontScaling={false}
          {...props}
        />
      </SmartlookSensitiveComponent>
      {secureTextEntry && (
        <TouchableOpacity onPress={() => setIsShown(prev => !prev)}>
          <FastImage
            source={
              !isShown
                ? require('~assets/icons/eye-inactive.png')
                : require('~assets/icons/eye-active.png')
            }
            style={{width: 20, height: 20}}
          />
        </TouchableOpacity>
      )}
    </View>
  );
} ```

**Relevant logs and/or screenshots**
No

**Comment by krystofcelba** [comment]
@usamaimam1 
Hey, thanks for your report. We are currently investigating the issue and soon we'll release a new version with fix.

**Comment by Muzzamil75** [comment]
@krystofcelba Still am not been able to make visible my Textinput (in iOS) by wrapping it in SmartlookSensitiveComponent hook.

Also upgraded to v1.2.5.
