### ISSUE TITLE
Wireframe mode records as native in Flutter

### ISSUE THREAD

**Issue by JohnyGQD** [smartlook/smartlook-mobile-issue-tracker#132]
**Platform**
Currently developing on Android 12

**Technology**
Flutter 2.8.1 (with sound null safety)

**Smartlook SDK version**
flutter_smartlook: ^3.0.5

**Summary**
I have tried to set the rendering mode in various phases of the SmartLook lifecycle, going as far as
```
Smartlook.setRenderingMode(SmartlookRenderingMode.wireframe);
Smartlook.setup(SetupOptionsBuilder(apiKey).build());
Smartlook.setRenderingMode(SmartlookRenderingMode.wireframe);
Smartlook.startRecording();
Smartlook.setRenderingMode(SmartlookRenderingMode.wireframe);
```
as well as in runtime, on specific events, but it still records the full screen. I have also tried to put the SmartlookHelperWidget in various places. Specifically the very root of the AppState, a little deeper right above the MaterialApp (as our root is Provider for dependency injection purposes), as well as the root of a specific route (as we use Navigator). Nothing seems to help. Is there any problem with using Provider or Navigator? Or is there anything else I might be forgetting?

**Comment by krystofcelba** [comment]
Hi,
could you please send me your smartlook account details in my email? -> krystof.celba@smartlook.com
I'll be able to help you more then.

Thanks!

**Comment by krystofcelba** [comment]
We are closing this issue as according to the info provided by @JohnyGQD, their organization uses the Free plan of Smartlook currently. The Wireframe mode is supported in our Business and Ultimate plan, for more info please check https://www.smartlook.com/pricing/ or contact us at sales@smartlook.com.

**Comment by JohnyGQD** [comment]
Thank you for your answer. I would suggest you to put some infobox in the API reference, or some clear debug information in either the app or the recording to indicate the issue.
