### ISSUE TITLE
Bridge

### ISSUE THREAD

**Issue by lamjay2704** [smartlook/smartlook-mobile-issue-tracker#134]
**Platform**

**Technology**

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

**Summary**

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by krystofcelba** [comment]
Hey @lamjay2704,
thanks for your bug report but it seems that you have forgotten to type in details about the issue you suffer. Could you please share the details with us, so we can help you properly?

Thanks!

**Comment by pavel-kroh-smartlook** [comment]
Abandoned issue template.
