### ISSUE TITLE
Error: virtual filesystem overlay file not found during debugging

### ISSUE THREAD

**Issue by Kondamon** [smartlook/smartlook-mobile-issue-tracker#136]
**Platform**

iOS

**Technology**

native

**Smartlook SDK version**

1.8.5

**Summary**
File is missing and debugging of project is not possible.

**Steps to reproduce [optional]**
1. Build project
2. Set breakpoint
3. Execute lldb command, e.g. 'po title'

**Example Project [optional]**

**Relevant logs and/or screenshots**

error: virtual filesystem overlay file '/Users/jezovec/Library/Developer/Xcode/DerivedData/Smartlook-chjxazzfvntsaygpoitrkmqkohzd/Build/Intermediates.noindex/ArchiveIntermediates/Smartlook/IntermediateBuildFilesPath/Smartlook.build/Release-iphoneos/Smartlook.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.

**Comment by pavel-kroh-smartlook** [comment]
Hi @Kondamon , 

cannot reproduce at this moment (trying an app with the Smartlook's production Swift Package). 

What Xcode version do you use (the package us build with 13.2.1 (13C100))? 

From a quick googling, it seem like a tricky issue with uncertain cause. We'll continue with the investigation tomorrow.

Pavel

**Comment by Kondamon** [comment]
@pavel-kroh-smartlook thanks for the quick reply. I guess you are testing the issue on a Mac with the user `/Users/jezovec/`?

I'll save you some hours, since I guess I have found the issue:

_When not using -no-serialize-debugging-options while building frameworks, the package is embedded with absolute paths for search paths etc._  [(source)](https://github.com/facebook/facebook-ios-sdk/issues/1628#issuecomment-771462320)

For reference, here are some details pointed out:
https://steipete.com/posts/couldnt-irgen-expression/

Please send best wishes to the sales team if they want to honour my debugging help. ;-)

**Comment by pavel-kroh-smartlook** [comment]
Yup, that is me, the `/Users/jezovec/`… 

I run in [a tweet by Peter Steinberger](https://twitter.com/steipete/status/1266669907858653184) yesterday, wanted to follow up the lead today, but thank you, I no longer need to - it is indeed the pesky dSYMs thing.

I'll check the recommended switch to see if it get us rid of the absolute paths… the whole xcframework and Swift Packages ecosystem seems to be heavily inclined to shared sources that compile locally.  

PS: send me your api key to `pavelkroh@smartlook.com` so the sales know who exactly you are ;-)

**Comment by pavel-kroh-smartlook** [comment]
Hi @Kondamon ,

we are working on a fix, we would like to know few more details about your setup (because we cannot reproduce it exactly, we see however some favourable difference when using `-no-serialize-debugging-options`), i.e., could you share with us 
- the Xcode version
- how is Smartlook added to the project (I remember you use Swift Package?)
- do you use some alternative package managers (Cocoapods, Carthage) in the project, too?

Thanks for the patience, the fix will be released soon.

**Comment by pavel-kroh-smartlook** [comment]
Hotfix version 1.8.6 with the fix is out.

**Comment by Kondamon** [comment]
@pavel-kroh-smartlook, didn't have a chance to respond earlier. 

Thank you very much for the quick fix! Can confirm it is fixed now!
