### ISSUE TITLE
Not getting new sessions from driver.

### ISSUE THREAD

**Issue by shilu-stha** [smartlook/smartlook-mobile-issue-tracker#139]
**Platform**
Android, iOS

**Technology**
React native

**Build instructions [optional]**
React Native version:  0.63.2
gradle dependencies: com.android.tools.build:gradle:4.0.0

**Rendering [optional]**
N/A

**Affected devices [optional]**
All Android: cipher lab phones, samsung

**Smartlook SDK version**
0.40.0

**Summary**
On a daily basis, we have around 100 drivers using our app.
However, we are not receiving any of their session recordings.

**Steps to reproduce [optional]**
N/A

**Example Project [optional]**
N/A

**Relevant logs and/or screenshots**
https://monosnap.com/file/loN4SpP1htAaunBEBiTKJlRi47sGsS

**Comment by krystofcelba** [comment]
Hey @shilu-stha,
It seems that you are using very old version of [smartlook-react-native-bridge](https://github.com/smartlook/smartlook-react-native-bridge), could you please try to update to [v1.2.5](https://github.com/smartlook/smartlook-react-native-bridge/releases/tag/v1.2.5)? It should fix your issue.
