### ISSUE TITLE
Could not find com.smartlook.recording:app:1.8.11.0-native-support. Required by:     project :app

### ISSUE THREAD

**Issue by Samuelungbede1** [smartlook/smartlook-mobile-issue-tracker#140]
**Platform**

**Technology**
**Kotlin**

**Build instructions [optional]**
gradle dependencies

**Rendering [optional]**
Specify how is your application rendered (Metal, OpenGL, Vulcan).

**Affected devices [optional]**

**Smartlook SDK version**
 implementation 'com.smartlook.recording:app:1.8.11.0-native-support'

**Summary**
 Could not find com.smartlook.recording:app
![Uploading Screenshot 2022-03-02 at 17.21.49.png…]()
:1.8.11.0-native-support. Required by:     project :app 

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**
``` 
Could not find com.smartlook.recording:app:1.8.11.0-native-support.
Required by:
    project :app
```

**Comment by Samuelungbede1** [comment]
<img width="1187" alt="Screenshot 2022-03-02 at 09 16 10" src="https://user-images.githubusercontent.com/63721672/156407239-67bdeec7-982e-4c7c-b0b7-e52f83de71d4.png">
<img width="1187" alt="Screenshot 2022-03-02 at 09 16 38" src="https://user-images.githubusercontent.com/63721672/156407254-29d3399b-5100-4b63-995f-5592f0b8bf5d.png">
<img width="1271" alt="Screenshot 2022-03-02 at 09 16 52" src="https://user-images.githubusercontent.com/63721672/156407260-0a508518-fe3d-4748-be2d-e9c4c95054da.png">
<img width="962" alt="Screenshot 2022-03-02 at 17 21 49" src="https://user-images.githubusercontent.com/63721672/156407265-b0a6f200-6a13-427c-a92e-074e22991227.png">

**Comment by SenNeonoveNoci** [comment]
Hello @Samuelungbede1,

I believe you have a typo in the SDK version it SHOULD be `1.8.11-native-support`, NOT `1.8.11.0-native-support`.

So the correct dependency looks like this:
```
implementation 'com.smartlook.recording:app:1.8.11-native-support'
```

_František Spurný
Android developer_
