### ISSUE TITLE
Screen is black on some recordings

### ISSUE THREAD

**Issue by LucasCoelho** [smartlook/smartlook-mobile-issue-tracker#141]
**Platform**
iOS

**Technology**
Native SwiftUI

**Smartlook SDK version**
1.8.6

**Summary**
Some of the recordings consist of black screen from the beginning to the end of the video. It's random, some users have sessions with black screen recordings and other sessions where everything looks fine.
A lot of our recordings have this problem.

**Steps to reproduce [optional]**
We weren't able to reproduce this issue on our devices. Our recordings look fine

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho ,

thanks for reporting. The "SwiftUI" is important - could you share with us how the application is setup (the Scenes and other "UI booting" stuff) - if I could guess, it seems that Smartlook might not properly find what is the root UI object to record in some cases?

**Comment by LucasCoelho** [comment]
I sent you an email

**Comment by pavel-kroh-smartlook** [comment]
Hi @LucasCoelho , thanks for the details. We are investigating the issue.

**Comment by vaclav-halik-smartlook** [comment]
Hi @LucasCoelho, i sent you an email with more informations.

**Comment by vaclav-halik-smartlook** [comment]
We haven't corrected the issue. The cause of the problem is unclear.

**Comment by LucasCoelho** [comment]
We noticed that initiating the screen recording manually, outside of the AppDelegate reduced significantly the number of black screens.
