### ISSUE TITLE
Need better docs for Xamarin.

### ISSUE THREAD

**Issue by dannyatger** [smartlook/smartlook-mobile-issue-tracker#147]
**Platform**

Both

**Technology**

Xamarin Forms.

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

**Summary**

Please update at least https://docs.smartlook.com/docs/sdk/xamarin?platform=xamarin so that others who use Xamarin Forms won't waste time trying to evaluate this product.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

See https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/145#issuecomment-1084244153

**Comment by pavel-kroh-smartlook** [comment]
Thanks for the remainder, the documentation was amended.
