### ISSUE TITLE
Android devices become stuck on splash screen

### ISSUE THREAD

**Issue by cmamessier** [smartlook/smartlook-mobile-issue-tracker#15]
**Platform**
Android

**Technology**
React native 0.61.5

**Affected devices**
All real android devices, not simulators

**Smartlook SDK version**
"smartlook-react-native-wrapper": "^0.33.0",

**Summary**
The app works well on iOS. On Android, it remains stuck on the splash screen. Once the call to `setupAndStartRecording` is removed from the code, then the application is working fine again. The screenshot below is an error that occurred before we remove the call to the function. 

**Relevant logs and/or screenshots**
![Screenshot_20201001-120956](https://user-images.githubusercontent.com/48687088/94955012-ec9a6600-04b7-11eb-8ef8-99ece389508d.png)

**Comment by SenNeonoveNoci** [comment]
Hi @cmamessier, thanks for the report, we will look at it on Monday.

**Comment by adamblack** [comment]
Hi @cmamessier ,

could you please share some code snippet with an example of how and where you call the SDK? Do you call anything else apart from setupAndStartRecording?

**Comment by cmamessier** [comment]
Hello, we have deleted the code by now, but essentially we were just importing the smartlook library in App.js, and then calling `setupAndStartRecording`. Nothing more.
