### ISSUE TITLE
React native webview not visible even using useSmartlookSensitiveRef

### ISSUE THREAD

**Issue by SandamalIsuru** [smartlook/smartlook-mobile-issue-tracker#152]
**Platform**
Both

**Technology**
React native

**Smartlook SDK version**
1.2.6

**Summary**
I am trying to whitelist react native WebView in Smartlook recordings. I have created a sample project and created and passed useSmartlookSensitiveRef reference to  WebView as mentioned in Smartlook documentation . But in the recordings WebView is still not showing.

This is my App.js file

`
import React, { useRef, useEffect } from 'react';
import {
  SafeAreaView,
  Text,
  useColorScheme,
  View,
} from 'react-native';
import { WebView } from 'react-native-webview';
import {
  Colors,
} from 'react-native/Libraries/NewAppScreen';
import Smartlook from 'smartlook-react-native-wrapper';
import { useSmartlookSensitiveRef } from 'smartlook-react-native-wrapper';
Smartlook.setupAndStartRecording("api_key");

const App = () => {
  const ref = useSmartlookSensitiveRef<WebView>(false);
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
      <View style={{alignItems: 'center', justifyContent: 'center', height: '100%', width: "100%"}}>
          <WebView ref={ref} source={{ uri: 'https://reactnative.dev/' }}
            style={{
              width: 320,
              height: 300,}} />
          </View>
    </SafeAreaView>
  );
};

export default App;
`

**Comment by krystofcelba** [comment]
@SandamalIsuru Hey, 
thanks for the issue reported. Could you please tell me what version of React Native you use? Or preferably, could you please contact me by email at krystof.celba@smartlook.com so we can discuss it better?

Thanks!
