### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.

### ISSUE THREAD

**Issue by erommartin** [smartlook/smartlook-mobile-issue-tracker#153]
**Platform**
both

**Technology**
Ionic

**Build instructions**
- ionic 6
- angular 13
- gradle 7.0.0
- kotlin: 1.6.10

**Smartlook SDK version**
cordova-plugin-smartlook 1.9.5

**Summary**
When generating apk the following error is shown:
`xxxx/.gradle/caches/transforms-3/fe6bd9fac933ef2de1db4486f9959bbd/transformed/jetified-app-1.8.11-cordova/jars/classes.jar!/META-INF/smartlooksdk_cordovaRelease.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.0.`

Thanks!

**Comment by SenNeonoveNoci** [comment]
@erommartin We are closing our GitHub issues and migrating all issue resolving to Intercom. Can you please write a follow up to [support@smartlook.com](mailto:support@smartlook.com).
