### ISSUE TITLE
Crashlytics integrations crashes on launch after compiling

### ISSUE THREAD

**Issue by mimitch2** [smartlook/smartlook-mobile-issue-tracker#154]
**Platform**
iOS - Android

**Technology**
React Native

**Build instructions [optional]**
React Native: 0.65.1

**Smartlook SDK version**
smartlook-react-native-wrapper:  1.2.6

**Summary**
I am trying to integrate crashlytics, and using a modified method to do so based on the docs (which appear to be incorrect: https://mobile.developer.smartlook.com/reference/react-native-integration-firebase-crashlytics#manual-integration), I keep crashing immediately when calling registerIntegrationListener.  

The docs appear to think that we should be passing in an object, but looking at the function, it sure seems that it just takes two callback parameters:  https://github.com/smartlook/smartlook-react-native-bridge/blob/16aa134fb11fe9f44d92160cd4cc2c32490c0202/src/Smartlook.ts#L365

I have modified my approach to reflect this, but it still crashes.                       

**Steps to reproduce [optional]**
My code:

```
	const onSessionReady = async (dashboardSessionUrl) => {
                await service.firebaseCrashlytics.setAttribute(
                    'dashboardSessionUrl',
                    dashboardSessionUrl
                );
            };
            const onVisitorReady = async (dashboardVisitorUrl) => {
                await service.firebaseCrashlytics.setAttribute(
                    'dashboardVisitorUrl',
                    dashboardVisitorUrl
                );
            };

            Smartlook.setUserIdentifier(`${service.userId}`, {
                ...idOfType,
                email: service.email,
                name: service.name,
                env,
            });

            Smartlook.registerIntegrationListener(onSessionReady, onVisitorReady);
            Smartlook.setupAndStartRecording(smartlookKey);

```
As soon as registerIntegrationListener is called, the app crashes.  I have tried calling the other Smartlook methods in different orders, but nothing appears to work.

**Relevant logs and/or screenshots**
![Screen Shot 2022-05-24 at 9 56 32 AM](https://user-images.githubusercontent.com/32558583/170066969-036224e5-d68c-40fc-9c15-348ea998ed65.png)

**Comment by SenNeonoveNoci** [comment]
@mimitch2  We are closing our GitHub issues and migrating all issue resolving to Intercom. Can you please write a follow up to [support@smartlook.com](mailto:support@smartlook.com).
