### ISSUE TITLE
Crashes reports on App Store with our iOS application on production

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [smartlook/smartlook-mobile-issue-tracker#155]
**Platform**
iOS
**Technology**
react native 

**Affected devices [optional]**

**Smartlook SDK version**
    "smartlook-react-native-wrapper": "^1.2.6",
**Summary**
we have multiple crashes on iOS production version on apple store 

**Relevant logs and/or screenshots**
![Screen Shot 2022-05-25 at 2 03 10 PM](https://user-images.githubusercontent.com/65596246/170464224-b64b1ca8-906c-427f-a6d6-93a45a6e75a9.png)

<img width="685" alt="Screen Shot 2022-05-26 at 12 51 52 PM" src="https://user-images.githubusercontent.com/65596246/170464335-9f404485-e589-474c-8168-38ff2bf19891.png">

**Comment by SenNeonoveNoci** [comment]
@ghadeeraqraa1992  We are closing our GitHub issues and migrating all issue resolving to Intercom. Can you please write a follow up to [support@smartlook.com](mailto:support@smartlook.com).
