### ISSUE TITLE
The recording is missing some screens

### ISSUE THREAD

**Issue by AMosa3d** [smartlook/smartlook-mobile-issue-tracker#16]
**Platform**
Android

**Technology**
Android Native with Java

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**
`implementation 'com.smartlook.recording:app:1.5.2-native'`

**Summary**
Some users' recordings are missing some general screens like the home screen for example but this is happening to a large percentage of the users. The implementation doesn't differ from the document implementation, we setup the sdk at `onCreate()` of the custom application and the recording is started at the Activity.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
Hi @AMosa3d,

can you please specify in detail when and how you start the recording? 
Also please can you run your Application with Smartlook logs enabled? You can enable them by adding this snipper before the SDK setup:
```
List<Integer> logAspects = new ArrayList<>();
logAspects.add(LogAspect.LIFECYCLE);
logAspects.add(LogAspect.SDK_METHODS);
logAspects.add(LogAspect.REST);
logAspects.add(LogAspect.VIDEO_CAPTURE);
Smartlook.debugLoggingAspects(logAspects);
```

**Comment by AMosa3d** [comment]
Hi @SenNeonoveNoci,

First, thank you for reply and time. Really grateful.

About when and how we start recording, it's a dynamic function that our back-end team manages, the start recording function are in a static function that is called from a LiveData observer with the home screen Lifecycle.

I have also tracked the log of the `Smartlook.debugLoggingAspects(logAspects);`, is there anything you would highlight that i should track in the logs.

**Comment by SenNeonoveNoci** [comment]
@AMosa3d Sorry I forgot to specify that. All Smartlook logs have `Smartlook` in the tag, so just filter out `Smartlook` and you can send all the logs.

**Comment by AMosa3d** [comment]
@SenNeonoveNoci It's okay totally never-mind.

Here is the logs:
`10-07 18:07:22.026 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onActivityStarted(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
10-07 18:07:22.026 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: Monitoring of RegisterationActivity STARTED
10-07 18:07:23.953 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onActivityResumed(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
10-07 18:07:24.260 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment zzc{7fcddbb} (ff47555d-90ef-4cea-9610-3f4affbe93b3) SupportLifecycleFragmentImpl} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
10-07 18:07:24.260 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment LoginPhoneFragment{e4b8631} (50759bf5-15c3-4ab5-8b27-b8491c84bea9) id=0x7f0a007c} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
10-07 18:07:24.519 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onActivityPaused(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
10-07 18:07:24.519 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentPaused() fragment zzc{7fcddbb} (ff47555d-90ef-4cea-9610-3f4affbe93b3) SupportLifecycleFragmentImpl} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
10-07 18:07:24.534 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentPaused() fragment LoginPhoneFragment{e4b8631} (50759bf5-15c3-4ab5-8b27-b8491c84bea9) id=0x7f0a007c} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
10-07 18:07:25.196 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onActivityStarted(tech.gplanet.shopx.ui.activities.CustomerMain@30da425)
10-07 18:07:25.196 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: Monitoring of CustomerMain STARTED
10-07 18:07:25.876 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onActivityResumed(tech.gplanet.shopx.ui.activities.CustomerMain@30da425)
10-07 18:07:26.241 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment CustomerHomeFragment{44e151b} (0b525d21-b8d9-4fda-9ce8-3bc63a552916) id=0x7f0a0272} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:26.479 8940-8940/tech.gplanet.shopx D/Smartlook_Smartlook: isRecording() called
10-07 18:07:26.479 8940-8940/tech.gplanet.shopx D/Smartlook_Smartlook: startRecording() called
10-07 18:07:26.479 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: Monitoring of CustomerMain STARTED
10-07 18:07:28.241 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{2782251} (1a1b4e78-794e-4c1a-b647-1d7307cee2e2) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:28.975 8940-9265/tech.gplanet.shopx D/Smartlook_a: [POST] https://manager.smartlook.com/rec/check/mobile/
10-07 18:07:28.982 8940-9175/tech.gplanet.shopx D/Smartlook_d: startNewRecording(): currentRecordedScreen=[CustomerMain] screenName=[RegisterationActivity]
10-07 18:07:28.983 8940-9175/tech.gplanet.shopx D/Smartlook_d: setupNewBatch(): screenName=[RegisterationActivity] forceNewBatch=[false]
10-07 18:07:28.983 8940-9175/tech.gplanet.shopx D/Smartlook_d: setupNewBatch(): stop video capture and create video
10-07 18:07:28.983 8940-9175/tech.gplanet.shopx D/Smartlook_d: stopVideoCaptureAndCreateVideo(): handleCrash=[false] sessionKey=[NZ9MI2ZKZ21H51134L] isFinal=[false]
10-07 18:07:28.983 8940-9175/tech.gplanet.shopx D/Smartlook_d: cancelVideoCapture()
10-07 18:07:28.983 8940-9175/tech.gplanet.shopx D/Smartlook_d: captureVideoSequenceIfPossible()
10-07 18:07:28.997 8940-9175/tech.gplanet.shopx D/Smartlook_d: startNewRecording(): currentRecordedScreen=[RegisterationActivity] screenName=[CustomerMain]
10-07 18:07:29.013 8940-9175/tech.gplanet.shopx D/Smartlook_d: keepSameBatch(): screenName=[CustomerMain]
10-07 18:07:29.253 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{9a9ffb1} (f4c91891-c69a-4043-a487-5ad632888db5) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:29.277 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{2782251} (1a1b4e78-794e-4c1a-b647-1d7307cee2e2) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:29.278 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{9a9ffb1} (f4c91891-c69a-4043-a487-5ad632888db5) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:29.280 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{b5d131b} (07d12b22-e2f8-4567-b264-0528007b7233) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:29.286 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{9a9ffb1} (671f848e-ea19-45af-81da-4cb81074addf) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:29.318 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment zzc{2c5b14c} (dd134b00-40e0-42df-9285-4339bc012cf4) SupportLifecycleFragmentImpl} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:29.329 8940-9265/tech.gplanet.shopx D/Smartlook_a: {"key":"xxxxxx","internalProps":{"platform":"Android","sdk_version":"1.5.2-native","sdk_build_id":"com.smartlook.sdk.smartlook","sdk_build_type":"release","sdk_build_flavor":"nativeapp","sdk_framework":"-","sdk_framework_version":"-","sdk_framework_plugin_version":"-","device":"unknown Android SDK built for x86","os_version":"6.0","os":"LOLLIPOP_MR1 23","userAgent":"Dalvik\/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build\/MASTER)","fingerprint":"Android\/sdk_google_phone_x86\/generic_x86:6.0\/MASTER\/5525988:userdebug\/test-keys","timezone":"Africa\/Cairo","bundle_id":"tech.gplanet.shopx","app_version_code":99,"app_version_name":"9.4.4","is_emulator":true,"is_rooted":true,"language":"ar","screen_density":2.625,"screen_resolution":"1080x1920","total_memory":1055469568,"total_heap_memory":28023416},"userAgent":"Dalvik\/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build\/MASTER)"}
10-07 18:07:29.351 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onActivityStopped(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
10-07 18:07:29.529 8940-9265/tech.gplanet.shopx D/Smartlook_a: Response with code: 200
10-07 18:07:29.569 8940-9265/tech.gplanet.shopx D/Smartlook_a: {"ok":true,"pid":"xxxxx","recording":{"ok":false,"sensitive":false,"error":"Reached project parallel limit","writerHost":"sdk-writer.eu.smartlook.cloud"},"analytics":{"ok":false,"writerHost":"events-writer.smartlook.com"},"options":{"storeGroup":"30d","maxRecordDuration":15000,"mobileBitrate":80000,"mobileFramerate":2,"mobileTargetHeight":360,"mobileData":false,"disableForms":false,"disableApi":false,"maskEmails":false,"maskNumbers":false,"signedDpa":false,"recordNetwork":false,"mobileRenderingMode":"native","canSwitchRenderingMode":false},"consent":{"ip":null,"api":null,"forms":null}}
10-07 18:07:30.360 8940-9276/tech.gplanet.shopx D/Smartlook_d: stopVideoCaptureAndCreateVideo(): handleCrash=[false] sessionKey=[NZ9MI2ZKZ21H51134L] isFinal=[true]
10-07 18:07:30.360 8940-9276/tech.gplanet.shopx D/Smartlook_d: cancelVideoCapture()
10-07 18:07:34.290 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{431925b} (c2080282-6daf-4ba1-9acd-2ed1ec137e1b) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:39.293 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{b5d131b} (07d12b22-e2f8-4567-b264-0528007b7233) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:44.304 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{b5d131b} (e7ac5304-205b-45e5-bcc7-1a6332df8638) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
10-07 18:07:44.645 8940-8940/tech.gplanet.shopx D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{431925b} (c2080282-6daf-4ba1-9acd-2ed1ec137e1b) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
`

If there is any sensitive data in the logs that I should have hid, please tell me, Thank you.

**Comment by AMosa3d** [comment]
@SenNeonoveNoci It's okay totally never-mind.

Here is the logs:
`D/Smartlook_Lifecycle: onActivityStarted(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
D/Smartlook_Lifecycle: Monitoring of RegisterationActivity STARTED
D/Smartlook_Lifecycle: onActivityResumed(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
D/Smartlook_Lifecycle: onFragmentResumed() fragment zzc{7fcddbb} (ff47555d-90ef-4cea-9610-3f4affbe93b3) SupportLifecycleFragmentImpl} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
D/Smartlook_Lifecycle: onFragmentResumed() fragment LoginPhoneFragment{e4b8631} (50759bf5-15c3-4ab5-8b27-b8491c84bea9) id=0x7f0a007c} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
D/Smartlook_Lifecycle: onActivityPaused(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
D/Smartlook_Lifecycle: onFragmentPaused() fragment zzc{7fcddbb} (ff47555d-90ef-4cea-9610-3f4affbe93b3) SupportLifecycleFragmentImpl} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
D/Smartlook_Lifecycle: onFragmentPaused() fragment LoginPhoneFragment{e4b8631} (50759bf5-15c3-4ab5-8b27-b8491c84bea9) id=0x7f0a007c} fragment activitytech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70
D/Smartlook_Lifecycle: onActivityStarted(tech.gplanet.shopx.ui.activities.CustomerMain@30da425)
D/Smartlook_Lifecycle: Monitoring of CustomerMain STARTED
D/Smartlook_Lifecycle: onActivityResumed(tech.gplanet.shopx.ui.activities.CustomerMain@30da425)
D/Smartlook_Lifecycle: onFragmentResumed() fragment CustomerHomeFragment{44e151b} (0b525d21-b8d9-4fda-9ce8-3bc63a552916) id=0x7f0a0272} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Smartlook: isRecording() called
D/Smartlook_Smartlook: startRecording() called
D/Smartlook_Lifecycle: Monitoring of CustomerMain STARTED
D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{2782251} (1a1b4e78-794e-4c1a-b647-1d7307cee2e2) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_a: [POST] https://manager.smartlook.com/rec/check/mobile/
D/Smartlook_d: startNewRecording(): currentRecordedScreen=[CustomerMain] screenName=[RegisterationActivity]
D/Smartlook_d: setupNewBatch(): screenName=[RegisterationActivity] forceNewBatch=[false]
D/Smartlook_d: setupNewBatch(): stop video capture and create video
D/Smartlook_d: stopVideoCaptureAndCreateVideo(): handleCrash=[false] sessionKey=[NZ9MI2ZKZ21H51134L] isFinal=[false]
D/Smartlook_d: cancelVideoCapture()
D/Smartlook_d: captureVideoSequenceIfPossible()
D/Smartlook_d: startNewRecording(): currentRecordedScreen=[RegisterationActivity] screenName=[CustomerMain]
D/Smartlook_d: keepSameBatch(): screenName=[CustomerMain]
D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{9a9ffb1} (f4c91891-c69a-4043-a487-5ad632888db5) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{2782251} (1a1b4e78-794e-4c1a-b647-1d7307cee2e2) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{9a9ffb1} (f4c91891-c69a-4043-a487-5ad632888db5) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{b5d131b} (07d12b22-e2f8-4567-b264-0528007b7233) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{9a9ffb1} (671f848e-ea19-45af-81da-4cb81074addf) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentResumed() fragment zzc{2c5b14c} (dd134b00-40e0-42df-9285-4339bc012cf4) SupportLifecycleFragmentImpl} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_a: {"key":"xxxxxx","internalProps":{"platform":"Android","sdk_version":"1.5.2native","sdk_build_id":"com.smartlook.sdk.smartlook","sdk_build_type":"release","sdk_build_flavor":"nativeapp","sdk_framework":"-","sdk_framework_version":"-","sdk_framework_plugin_version":"-","device":"unknown Android SDK built for x86","os_version":"6.0","os":"LOLLIPOP_MR1 23","userAgent":"Dalvik\/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build\/MASTER)","fingerprint":"Android\/sdk_google_phone_x86\/generic_x86:6.0\/MASTER\/5525988:userdebug\/test-keys","timezone":"Africa\/Cairo","bundle_id":"tech.gplanet.shopx","app_version_code":99,"app_version_name":"9.4.4","is_emulator":true,"is_rooted":true,"language":"ar","screen_density":2.625,"screen_resolution":"1080x1920","total_memory":1055469568,"total_heap_memory":28023416},"userAgent":"Dalvik\/2.1.0 (Linux; U; Android 6.0; Android SDK built for x86 Build\/MASTER)"}
D/Smartlook_Lifecycle: onActivityStopped(tech.gplanet.shopx.ui.activities.RegisterationActivity@1f5eb70)
D/Smartlook_a: Response with code: 200
D/Smartlook_a: {"ok":true,"pid":"xxxxx","recording":{"ok":false,"sensitive":false,"error":"Reached project parallel limit","writerHost":"sdk-writer.eu.smartlook.cloud"},"analytics":{"ok":false,"writerHost":"events-writer.smartlook.com"},"options":{"storeGroup":"30d","maxRecordDuration":15000,"mobileBitrate":80000,"mobileFramerate":2,"mobileTargetHeight":360,"mobileData":false,"disableForms":false,"disableApi":false,"maskEmails":false,"maskNumbers":false,"signedDpa":false,"recordNetwork":false,"mobileRenderingMode":"native","canSwitchRenderingMode":false},"consent":{"ip":null,"api":null,"forms":null}}
D/Smartlook_d: stopVideoCaptureAndCreateVideo(): handleCrash=[false] sessionKey=[NZ9MI2ZKZ21H51134L] isFinal=[true]
D/Smartlook_d: cancelVideoCapture()
D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{431925b} (c2080282-6daf-4ba1-9acd-2ed1ec137e1b) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{b5d131b} (07d12b22-e2f8-4567-b264-0528007b7233) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentResumed() fragment AnnouncementCarouselFragment{b5d131b} (e7ac5304-205b-45e5-bcc7-1a6332df8638) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425
D/Smartlook_Lifecycle: onFragmentPaused() fragment AnnouncementCarouselFragment{431925b} (c2080282-6daf-4ba1-9acd-2ed1ec137e1b) id=0x7f0a00eb} fragment activitytech.gplanet.shopx.ui.activities.CustomerMain@30da425`

If there is any sensitive data in the logs that I should have hid, please tell me, Thank you.

**Comment by SenNeonoveNoci** [comment]
Closed fo inactivity.
