### ISSUE TITLE
Smart look not integrated when minifyEnabled is true in bundled app

### ISSUE THREAD

**Issue by missyadavmanisha** [smartlook/smartlook-mobile-issue-tracker#21]
**Platform** Android

**Technology** Java

**Rendering [optional]**

**Affected devices [optional]**  Run time issue in every device

**Smartlook SDK version** 1.5.3

**Summary**
I am trying to integrate the smart look in my android app but while integrating if minifyEnabled is true then it gives me an error that **minifyreleaseR8 failed because Type a.a.a.a is defined multiple times in build/Intermediates/modules_and_runtime_deps_classes/release/base.jar** but if mindEnabled is false it runs perfectly but the size of the app is increased by 5 Mb
**Bundling is Enabled in app**

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by adamblack** [comment]
Hi @missyadavmanisha ,

could you share dependencies of your app, please? Is it possible that you add i.e. JAR deps instead of gradle ones? SDK uses only Kotlin as a dependency on POM definition (kotlin-stdlib-jdk8).

Also, there is a newer version of the SDK, 1.6.0.

**Comment by missyadavmanisha** [comment]
Hey,

How I can add jar dependency, is there any dic available for that. Because
I am still getting error.

**Comment by adamblack** [comment]
Hi @missyadavmanisha,

did you try to i.e. exclude kotlin dependency from an external jar or even from our lib? That should do the trick I believe.
