### ISSUE TITLE
Unity Android Crash

### ISSUE THREAD

**Issue by islam0talha** [smartlook/smartlook-mobile-issue-tracker#22]
**Platform** Android
**Technology** Unity
**Smartlook SDK version** 1.6.0

**Summary**
The game freezes randomly in many places more often after starting a purchase (Unity IAP), cancelling it, then tapping any where on the screen

**Steps to reproduce**
Start a purchase (Unity IAP), cancelling it, then tapping any where on the screen

**Comment by adamblack** [comment]
Fixed in new version 1.6.2
