### ISSUE TITLE
Forbidden - Production Environment

### ISSUE THREAD

**Issue by GTBulla** [smartlook/smartlook-mobile-issue-tracker#23]
**Platform**
Android

**Technology**
kotlin

**Smartlook SDK version**
1.5.3

**Summary**
I can't record in production environment. I get the error: https://manager.smartlook.com/rec/check/mobile/, Response code: 403
But in a development environment I can: https://manager.smartlook.com/rec/init/mobile/, Response code: 200
I use the Smartlook.setupAndStartRecording (key) method to start. Obs: key is smartlook key, an for production and other for development.

**Comment by SenNeonoveNoci** [comment]
Hi, @GTBulla, can you please send me your API key to frantisek@smartlook.com?

We need to see your project to investigate this issue.

**Comment by GTBulla** [comment]
I sent the email with API key

**Comment by SenNeonoveNoci** [comment]
@GTBulla You should see this message in your dashboard:

```
You’re not recording some of the visitors right now
Free accounts are limited to recording 10 people at the same time. Your traffic is higher than that.
```

You are hitting the parallel limit of recording, so `check` will not allow the recording.
