### ISSUE TITLE
Black/blank recordings in Android NDK/OpenGL app.

### ISSUE THREAD

**Issue by yglukhov** [smartlook/smartlook-mobile-issue-tracker#26]
**Platform**
Android

**Technology**
SDL2, NDK

**Rendering [optional]**
OpenGL

**Affected devices [optional]**
All?..

**Smartlook SDK version**
1.6.1-native

**Summary**
Recordings are black/blank in an SDL/OpenGL app

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
Hi @yglukhov, have you set `experimental` flag to `true`?
https://smartlook.github.io/docs/sdk/api-reference?platform=android#setup-configuration

Please try that and update us if it helps.

**Comment by yglukhov** [comment]
That nailed it. Thanks a bunch!
