### ISSUE TITLE
Android/OpenGL recordings are mostly blank

### ISSUE THREAD

**Issue by yglukhov** [smartlook/smartlook-mobile-issue-tracker#27]
**Platform**
Android

**Technology**
NDK, SDL2, OpenGL

**Rendering [optional]**
OpenGL

**Affected devices [optional]**
All?

**Smartlook SDK version**
 1.6.1-native

**Summary**
Recordings contain only a second-long footage which is "stuck" for a while and then disappears entirely to blank/black screen. It seems almost as if the [ui change detection feature](https://smartlook.github.io/docs/sdk/conceptual/when-the-recordings-appear-in-dashboard?platform=android#recording-limitations) doesn't detect the changes in OpenGL surface.

Note: experimental recording is enabled.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
```
It seems almost as if the ui change detection feature doesn't detect the changes in OpenGL surface.
```

Hi @yglukhov, I think you are right, let me prepare test build with adaptive framerate disabled. If this fixes the issue, we gonna prepare some API method to disable the feature.

**Comment by SenNeonoveNoci** [comment]
@yglukhov please try this build:
```
implementation 'com.smartlook.recording:app:1.6.1-native-no-adaptive'
```

**Comment by yglukhov** [comment]
> please try this build

It works now! Thank you! However the "good" footage was appended to the end of existing session with bad footage even though the build is different, but I guess that's a different question. Can I use the `native-no-adaptive` version until the official fix is out?

**Comment by SenNeonoveNoci** [comment]
Sure feel free to use this version. It's based on the latest release only with so-called "adaptive framerate" disabled.
Also, you can read more about sessions:
https://smartlook.github.io/docs/sdk/conceptual/when-the-recordings-appear-in-dashboard?platform=android

And you can force the creation of a new session on application start like this:
https://smartlook.github.io/docs/sdk/api-reference?platform=android#reset-session

I'm gonna close the issue for now, in the next version of SDK we will method that's gonna allow you to disable adaptive framerate.

**Comment by yglukhov** [comment]
There's a new 1.6.2 version out there, but I can't find any release notes nor related changes in the API reference. Has this issue been addressed there?
