### ISSUE TITLE
Could not find com.smartlook.recording:app:1.6.2-native.

### ISSUE THREAD

**Issue by hussnainmuavia** [smartlook/smartlook-mobile-issue-tracker#32]
**Android**

**Kotlin**

*Affected devices [Android Phones]*

*SmartLook SDK version: 1.6.2*

**Summary**
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.smartlook.recording:app:1.6.2-native.

**Steps to reproduce**
**I have added this in build.gradle(:app)**
dependencies {

    implementation 'com.smartlook.recording:app:1.6.2-native'
}

**and in build.gradle at project level file I have added.**

    repositories {
         maven { url "https://plugins.gradle.org/m2/" }
         maven { url "https://sdk.smartlook.com/android/release" }
         google()
         jcenter()
     }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }

**Build Output Error**

Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.smartlook.recording:app:1.6.2-native.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/smartlook/recording/app/1.6.2-native/app-1.6.2-native.pom
       - https://jcenter.bintray.com/com/smartlook/recording/app/1.6.2-native/app-1.6.2-native.pom
       - file:/C:/Users/hussnain.muavia/Documents/NovelHealth-Android/amazon-chime-sdk/libs/app-1.6.2-native.jar
       - file:/C:/Users/hussnain.muavia/Documents/NovelHealth-Android/amazon-chime-sdk/libs/app.jar
     Required by:
         project :app

**Comment by SenNeonoveNoci** [comment]
Hi @hussnainmuavia, you have added:
```
maven { url "https://sdk.smartlook.com/android/release" }
```
where it doesn't belong, you should place it in **_allprojects_**:
```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://sdk.smartlook.com/android/release" }
    }
}
```

Full sample project `build.gradle` file:
```
buildscript {
    repositories {
        // Smartlook maven repository does not belong here
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://sdk.smartlook.com/android/release" }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by hussnainmuavia** [comment]
@SenNeonoveNoci Thank you so much, it works fine now
