### ISSUE TITLE
Cannot make XCFramework

### ISSUE THREAD

**Issue by kamranpirwani** [smartlook/smartlook-mobile-issue-tracker#34]
**Platform**
iOS

**Technology**
Native

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**
v1.5.0

**Summary**
We have an internal repo built through Cocoapods we would like to pull Smartlook into, then integrate this into our main project. Because Smartlook is distributed as a fat framework, unable to make an xcframework from it and package as a vendored framework using CocoaPods

Since this is a private library we are unable to build manually for Simulator + iPhone and make an XCFramework.

Running the command to convert this into an XCFramework fails with:
```error: binaries with multiple platforms are not supported ```

**Steps to reproduce [optional]**
- Try to make an XCFramework using:
```
xcodebuild -create-xcframework \
           -framework Smartlook.framework \
           -output archives/YourFramework.xcframework
```

**Example Project [optional]**

**Relevant logs and/or screenshots**
```error: binaries with multiple platforms are not supported ```

**Comment by pavel-kroh-smartlook** [comment]
Hi, we will look into distributing Smartlook as an xcframework. 

In the meantime, Smartlook is also distributed as a `Smartlook` Cocoapod that could perhaps be used as an external dependency in your building system.

**Comment by kamranpirwani** [comment]
Thanks for the quick response. The issue is including this as a dependency in a framework which is used in another application is not working as a pod

**Comment by pavel-kroh-smartlook** [comment]
Hi @kamranpirwani , we just released a new version in the form of XCFramework, for direct download here: https://sdk.smartlook.com/ios/smartlook-ios-sdk-1.7.0.2975.zip

**Comment by pavel-kroh-smartlook** [comment]
Issue solved by publishing the official XCFramework.
