### ISSUE TITLE
Sessions on some devices are not being recorded

### ISSUE THREAD

**Issue by R3621** [smartlook/smartlook-mobile-issue-tracker#35]
**Platform**
Android

**Technology**
React native

**Affected devices [optional]**
Xiaomi Redmi Note 7

**Smartlook SDK version**
1.6.0-react

**Summary**
Sessions from my device are not being recorded. When I open the app, I can see my session in Active Sessions, but I can't see it. I can see Recording is not available yet caption instead. Also, the number of pages is always 0, and the session length is always 0:00. I try to use the app and open and view different pages, but it doesn't change. Even after I kill the app, I still see the active session. Though it never goes to All visitors, just disappears. Recording example is https://app.smartlook.com/c0ffeff37f53f0d4d6c1692c/recordings/player/di_1nQKnw/6-6_EJYoOQ

**Relevant logs and/or screenshots**
![image](https://user-images.githubusercontent.com/46097753/100546024-0bc33300-3270-11eb-8f53-85e8394a6c3b.png)
![image](https://user-images.githubusercontent.com/46097753/100546035-27c6d480-3270-11eb-9e0d-4ffcc287616d.png)

**Comment by SenNeonoveNoci** [comment]
Hi @R3621,

are you recording when you are connected to WiFi?

**Comment by R3621** [comment]
Hi @SenNeonoveNoci 

Nope, I was on 4G connection.

**Comment by SenNeonoveNoci** [comment]
> Hi @SenNeonoveNoci
> 
> Nope, I was on 4G connection.

This is the problem. By default, records are only uploaded on Wifi. We create the sessions using moile connection, but we do not upload the record because the might drain the user's data.

This behaviour can be changed in the dashboard. In project settings, you can enable `Upload on mobile (cellular) data`.

But please try to make some recordings on a Wifi connection. Everything should work as expected.

**Comment by R3621** [comment]
Thank you @SenNeonoveNoci 

Do you have any estimations of what would be the additional data size needed to upload the recording from the device?

**Comment by SenNeonoveNoci** [comment]
> Do you have any estimations of what would be the additional data size needed to upload the recording from the device?

@R3621 Depends on selected video quality:

Preset | Bitrate | Maximal bandwidth
-- | -- | --
Low | 80 000 bits/s | ~ 0.5 MB per minute
Medium | 160 000 bits/s | ~ 1 MB per minute
High | 320 000 bits/s | ~ 2 MB per minute

More about this topic can be found in our [documentation](https://smartlook.github.io/docs/sdk/conceptual/screen-recording-quality/?platform=android).
