### ISSUE TITLE
No such file or directory warnings

### ISSUE THREAD

**Issue by khaliddd** [smartlook/smartlook-mobile-issue-tracker#36]
Hello, 

I am getting lots of warnings while compiling, Please look at the attached screenshot. 

how can i fix it, these are really annoying. 

![Screen Shot 2020-11-30 at 3 19 04 PM](https://user-images.githubusercontent.com/2604040/100598074-0f15f780-3320-11eb-97b1-ba04776b57d1.png)

**Comment by pavel-kroh-smartlook** [comment]
Hi @khaliddd , 

thanks for reporting it, we are aware about this issue.

It will be fixed in the next release of Smartlook, soon.

**Comment by pavel-kroh-smartlook** [comment]
The current release (1.7.0) has solved this issue.
