### ISSUE TITLE
file upload gallery view is visible

### ISSUE THREAD

**Issue by kislasi** [smartlook/smartlook-mobile-issue-tracker#37]
I've been asked by your support team to open this issue here.
on android, when the user open the gallery it is been recorded:
![gallery 1](https://user-images.githubusercontent.com/33934822/100739191-64fda480-33df-11eb-8739-a95d340e4d4b.PNG)

Thanks.

**Comment by SenNeonoveNoci** [comment]
Hi, @kislasi can you specify your issue further:
- What version of SDK are you using?
- The Gallery is outside your application context?
- If the gallery is part of your application did you consider to hide it using SDKs ability to hide sensitive views?

**Comment by kislasi** [comment]
Hi @SenNeonoveNoci,

SDK version: com.smartlook.recording:app:1.6.2-native
I’m m using MultiType-FilePicker which open the client gallery.

i don’t t think its something that I can control...

thanks.

**Comment by SenNeonoveNoci** [comment]
@kislasi The picker is a part of your Application even though the implementation is in [library](https://github.com/fishwjy/MultiType-FilePicker) So yes we are recording it. 

You can disable the recording of the given part by using `RenderingMode.NO_RENDERING` (explained [here](https://smartlook.github.io/docs/sdk/api-reference?platform=android#no-rendering)).

Small example:

- starting file picker:
```
Intent intent = new Intent(this, ImagePickActivity.class);
intent.putExtra(IS_NEED_CAMERA, true);
intent.putExtra(Constant.MAX_NUMBER, 9);

// Do not capture screen from this point
Smartlook.setRenderingMode(RenderingMode.NO_RENDERING);

startActivityForResult(intent1, Constant.REQUEST_CODE_PICK_IMAGE);
```

- receiving a result from file picker:
```
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {

  // Process the result

  // Capture screen from this point
  Smartlook.setRenderingMode(RenderingMode.NATIVE);
}
```
