### ISSUE TITLE
Long time app launch

### ISSUE THREAD

**Issue by IbragimovDP** [smartlook/smartlook-mobile-issue-tracker#39]
After adding smartlook as framework app launch time is about 11 sec.
And there is warning about threads:
![image](https://user-images.githubusercontent.com/60131800/100900995-7674a880-34d4-11eb-90ac-86fc2b05ce84.png)
![image](https://user-images.githubusercontent.com/60131800/100901026-7bd1f300-34d4-11eb-9825-d748a431cc84.png)

**Platform**

iOS

**Technology**

SwiftUI

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

Don't know where can look it. Installed today couple hours ago.

**Summary**

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
Hi @IbragimovDP, this is a known thing, please read [here](https://smartlook.github.io/docs/sdk/cookbooks/ios-main-thread-check-warning?platform=ios).

**Comment by IbragimovDP** [comment]
Hi @SenNeonoveNoci , thanks a lot!

**Comment by SenNeonoveNoci** [comment]
@IbragimovDP No problem! I hope you gonna fully enjoy Smartlook now.
