### ISSUE TITLE
Found an unexpected Mach-O header code: 0x72613c21

### ISSUE THREAD

**Issue by khaliddd** [smartlook/smartlook-mobile-issue-tracker#43]
Hello, 

I am using smartlook ios SDK via SPM, Its working fine, but when I archive and try to upload build on itunes and get this error: 

"Found an unexpected Mach-O header code: 0x72613c21"

it was not there when I was using older version via cocoapods.

**Comment by pavel-kroh-smartlook** [comment]
Hi @khaliddd , after some investigation we found that Xcode and SPM do not handle static libraries in binary SP well.

We rebuild Smartlook as a dynamic library and published it in `dynamic_library` branch. 

Could you please check this branch in SPM and let us know if it works for you? 

Note: it seems it is necessary to clean all caches throughly when updating this way…

**Comment by pavel-kroh-smartlook** [comment]
Hi again, I run some more tests myself a the `dynamic_library` branch does not seem working, either.

SPM for binary packages is apparently broken.

For now, either 
- use our Cocoapod (that, however, cannot be used in arm simulator apps due to Cocoapods own limitations), 
- or manually add XCFramework (not via SPM) and flag the embedded library as "Do Not Embed"
- [not tested by us] check the extra manual steps as described in e.g., https://github.com/firebase/firebase-ios-sdk/issues/6472

**Comment by pavel-kroh-smartlook** [comment]
Hi again @khaliddd , we found an elegant workaround for SPM.

After adding the package, navigate to the **Swift Package Dependencies** in your Project navigator and drop the `Smartlook.xcframwork` from there to **Frameworks, Libraries and Embedded Content** in your project target. Then you can switch the **Embed** type to the **Do Not Embed** value necessary for static libraries. 

<img width="944" alt="Setup_static_Swift_package" src="https://user-images.githubusercontent.com/44899602/102332677-b2a41080-3f8c-11eb-8309-22566ccdf807.png">

**Comment by khaliddd** [comment]
@pavel-kroh-smartlook okay thank you, I'll try it today.

**Comment by khaliddd** [comment]
@pavel-kroh-smartlook getting error while adding via spm. 

![Screen Shot 2020-12-16 at 4 21 08 PM](https://user-images.githubusercontent.com/2604040/102342792-8bb10300-3fbb-11eb-8321-3f4d83e3906a.png)

**Comment by pavel-kroh-smartlook** [comment]
@khaliddd : I got similar problems first, removing the package, clean and deleting derived data, and adding package back helped.

**Comment by pavel-kroh-smartlook** [comment]
Solution described in our documentation: https://smartlook.github.io/docs/sdk/cookbooks/swift-package-app-store-mach-o-error?platform=ios
