### ISSUE TITLE
Cocos Journey Not working After SDK installation

### ISSUE THREAD

**Issue by tanya-games24x7** [smartlook/smartlook-mobile-issue-tracker#44]
**Platform**
Android

**Technology**
Cocos

**Smartlook SDK version**
1.7.0

**Summary**
The smartlook recording for Cocos journey on the android app shows a black screen and not the journey being performed.

**Relevant logs and/or screenshots**
https://app.smartlook.com/play/shared/01ed84aab3c5f1b08019ff6bdd77f5a600ca4057 find the recording here, the journey in black is in cocos

**Comment by adamblack** [comment]
Recordings on cocos are currently supported for API 24+.
