### ISSUE TITLE
Not working in iOS release build

### ISSUE THREAD

**Issue by Inderpal610** [smartlook/smartlook-mobile-issue-tracker#45]
Got recording data  in **debug** build but in **release** build no data found in dashboard.

**Comment by pavel-kroh-smartlook** [comment]
Hi @Inderpal610 , provide please more detail about the way Smartlook is integrated (Swift package, direct embedding. Cocoapods), the technology you use for the app (native, some 3rd party framework). Also send me please the API key of you project to email `pavelkroh+38457@smartlook.com` if you will. Thanks.

**Comment by pavel-kroh-smartlook** [comment]
Hi @Inderpal610 , thanks for the additional info in your email. The situation is quite strange, the SDK version 1.5.0 is in production for few months and seems working for others. We're investigating it now on our server side.

**Comment by Inderpal610** [comment]
Hi @pavel-kroh-smartlook any update?

**Comment by pavel-kroh-smartlook** [comment]
Hi @Inderpal610 , sorry for delay in communication, there is no straightforward explanation for the issue and it seems also related to our backend. A backend colleague is working on it full time now.

**Comment by pavel-kroh-smartlook** [comment]
Hi @Inderpal610 , 

1. we have found that our SDK in your app does not communicate with one of our backends (sends no request to it), the backend domain is `events-writer.smartlook.com`.  Without the data sent there, the analytics on the data is not possible, even though the events appear in the player. This is the first time we see this kind of issue in any app.

2. we also found that you do not use the last version of API (1.7.1), although this is not cause of the issue.

Could you please check if the iOS app does not accidentally block the  `events-writer.smartlook.com` domain, or if there are no messages in logs related to this communication? Upgrading the SDK would be nice, but is not critical at this moment.

Thanks.

**Comment by Inderpal610** [comment]
Ok, I will check.

**Comment by pavel-kroh-smartlook** [comment]
Issue abandoned by the creator.
