### ISSUE TITLE
Wireframe rendering mode option messes up the UI of the app

### ISSUE THREAD

**Issue by rottenbergnirvon** [smartlook/smartlook-mobile-issue-tracker#46]
**Platform**
Android

**Technology**
native

**Rendering [optional]**
Wireframe

**Affected devices [optional]**
Emulators and real devices

**Smartlook SDK version**
1.7.0-native

**Summary**
When I use wireframe rendering mode with wireframe rendering mode option, the screens of the app start to mess up after working with it for a bit. It seems like when I switch between screens the ui of the previous screen still appears, after moving between several screens almost all of the screen is black.

When I switch to blueprint rendering mode option (still wireframe rendering mode) it works fine.

One more question, on blueprint mode option whitelisting views doesn't work, is that intended?

**Steps to reproduce [optional]**
Navigate around the app a bit and it starts to happen

**Relevant logs and/or screenshots**
Here is a part of the screen when it is messed up:

<img width="390" alt="Screen Shot 2020-12-22 at 12 26 38" src="https://user-images.githubusercontent.com/62010871/102879156-0bbee900-4452-11eb-9450-d7aeb5a980ec.png">

**Comment by SenNeonoveNoci** [comment]
Hi @rottenbergnirvon,

I want to clear one thing up, `WIREFRAME` rendering mode messes up the UI of your application or only the recordings are messed up in Smartlook dashboard?

Is there any chance to download your application anywhere so we can take a look?

Also please send me your Smartlook `API key` to frantisek@smartlook.com. Thanks!

**Comment by rottenbergnirvon** [comment]
It messes up the UI of the application.
I just sent you an email, thanks!

**Comment by SenNeonoveNoci** [comment]
@rottenbergnirvon Without seeing the app its might be a challenge to solve but I have one idea. I'm gonna prepare a special build for you with our new experimental wireframe mode.
We will see if it helps the situation. It will be ready tomorrow.

**Comment by SenNeonoveNoci** [comment]
@rottenbergnirvon Can you please try this version of sdk:
```
implementation 'com.smartlook.recording:app:1.7.0-native-experimental-rendering'
```
Note that this is a new experimental implementation, so it's not suitable for production usage. But if it helps your problem I have an idea of what might be wrong.

**Comment by rottenbergnirvon** [comment]
Thanks @SenNeonoveNoci , this version solves the issue. When can I expect it to be released on a non-experimental version?

Also about whitelisting views, does that work with wireframe rendering too?

**Comment by SenNeonoveNoci** [comment]
@rottenbergnirvon If you test it on your application and everything works, you can use this version. It's the same as stable SDK version but with changed wireframe mode. The official release is gonna be out sometime in January, currently, I'm not able to provide more specific date now.

About the "whitelisting", SDK currently doesn't have this functionality. But thanks for the suggestion, we gonna implement it in some future version.

**Comment by rottenbergnirvon** [comment]
Thanks @SenNeonoveNoci
