### ISSUE TITLE
Framework not found Smartlook.xcframework clang: error: linker command failed with exit code 1

### ISSUE THREAD

**Issue by vivekverma1993** [smartlook/smartlook-mobile-issue-tracker#47]
**Platform**

both
**Technology**

React Native
**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

0.39.0
**Summary**

After following installation with React native docs, android is working fine but build fails on ios with the error Framework not found Smartlook.xcframework
**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

```
ld: framework not found Smartlook.xcframework
clang: error: linker command failed with exit code 1
```

**Comment by pavel-kroh-smartlook** [comment]
Hi @vivekverma1993 : on what OS version do you build this? Is it arm64 macOS by a chance?

**Comment by vivekverma1993** [comment]
yes

**Comment by pavel-kroh-smartlook** [comment]
Could you please try to build this for a device, not a simulator and let us know if it works? 

Unfortunatelly, Cocoapods do not support xcframeworks that have both simulator and real device binary library version on arm64.

**Comment by vivekverma1993** [comment]
i tried running on iPhone 7 plus, got the same error.

**Comment by pavel-kroh-smartlook** [comment]
I see, thanks, will look into it.

**Comment by pavel-kroh-smartlook** [comment]
Hi @vivekverma1993 , I've managed to create and run a RN app with the latest Smartlook on arm64 macOS (I use it myself). Could you check the Cocoapods version (`pod --version`) you have? The latest is `1.10.1`.

**Comment by vivekverma1993** [comment]
Hi @pavel-kroh-smartlook we are using Pod version 1.8.4

**Comment by pavel-kroh-smartlook** [comment]
Hi @vivekverma1993 , this is probably the problem, XCFrameworks may not be supported in older Cocoapods. Could you upgrade them?

**Comment by vivekverma1993** [comment]
It worked after updating Cocoapods to latest version 🥳
