### ISSUE TITLE
slSensitive property not appearing in IB Inspector

### ISSUE THREAD

**Issue by UrosZivaljevic** [smartlook/smartlook-mobile-issue-tracker#48]
**Platform**

iOS
**Technology**

Swift
**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

1.7.1
**Summary**

UIView property `slSensitive` does not appear in Interface Builder inspector
**Steps to reproduce [optional]**

Select any view in storyboard/xib file and check IB Inspector tab on right side

**Example Project [optional]**

**Relevant logs and/or screenshots**

![image](https://user-images.githubusercontent.com/26653922/104006900-6de45180-51a7-11eb-83e9-20a2c4a942ed.png)

**Comment by pavel-kroh-smartlook** [comment]
Hi @UrosZivaljevic , we are aware about this issue and honestly, we do not know why it is not there. We expect that this is some Xcode issue as we did not change anything related to them in our SDK. We tried to find some solution, but so far with no avail.

**Comment by UrosZivaljevic** [comment]
Weird 😕 

Okay, until then I'll make an UIView extension with:

```
@IBInspectable var smartlookSensitive: Bool {
        get { return slSensitive }
        set { self.slSensitive = newValue }
}
```

**Comment by pavel-kroh-smartlook** [comment]
Nice workaround indeed! 

However, weird it is as you said, it worked fine out of the box for long time. Perhaps it is somehow related to the move from frameworks to xcframeworks and `@IBDesignable` from external xcframeworks are no longer supported , maybe the `@IBDesignable` is lost somewhere in xcframework compilation…  :-(

We will definitively try to fix it as it is a nice useful feature but we are not sure it is possible.

**Comment by pavel-kroh-smartlook** [comment]
I googled a bit and run some tests again. It seems that the ability to import inspectables from external frameworks was removed, the `@IBInspactable` is simply ignored. We will look into it periodically in the future to see if this changed, but as for now, this is apparently not fixable.
