### ISSUE TITLE
Some recordings are missing from iOS

### ISSUE THREAD

**Issue by krish23** [smartlook/smartlook-mobile-issue-tracker#51]
Platform
iOS

Technology
iOS Native Xcode

Smartlook SDK version
1.2.7

We could notice that some recordings are missing from iOS app. As we checked, from same IP address we could see only one recording session. However, we could observe from our backend that the user had many activities but all those recordings are missing.

**Comment by pavel-kroh-smartlook** [comment]
Hi @krish23 , send me please your API key by email to: `pavelkroh@smarltook.com` so we can check the related activity on our backend side. Thanks.

**Comment by pavel-kroh-smartlook** [comment]
Issue abandoned by its author.
