### ISSUE TITLE
IOS - Blacklisting is not working after submitting a form

### ISSUE THREAD

**Issue by gnsuluturk** [smartlook/smartlook-mobile-issue-tracker#52]
**Platform**
iOS

**Technology**
native

**Smartlook SDK version**
iOS 1.7.1

**Summary**
On our iOS app,  for credit card screen we are masking the form fields but when pay button is clicked it starts to display the card form fields in loading state. We are not experiencing this on Android side, can you help with this?

**Relevant logs and/or screenshots**
Example recording with timestamp.
https://app.smartlook.com/play/shared/3b907821a432557fba0f9b5e17626223ecf3cca9?time=85500
Before
![image](https://user-images.githubusercontent.com/64907734/105172490-c107be00-5b30-11eb-8e8f-42b92e79d99c.png)
After
![image](https://user-images.githubusercontent.com/64907734/105172503-c9f88f80-5b30-11eb-94f0-bb5d7b3576a1.png)

**Comment by pavel-kroh-smartlook** [comment]
Hi @gnsuluturk , we are aware that this may happen and work on a fix. In meantime you can switch to wireframe mode for this form. Also, send me please please your API key by email to: pavelkroh@smarltook.com so we can extract some debug information about your project from our backend. Thanks.

**Comment by pavel-kroh-smartlook** [comment]
Thanks, we look into it and expect to release a fix next week.

**Comment by pavel-kroh-smartlook** [comment]
Hi @gnsuluturk , we just released new version 1.7.2 that should fix this issue. It is available via all the regular channels: https://smartlook.github.io/docs/sdk/ios?platform=ios
