### ISSUE TITLE
WebView is not recorded

### ISSUE THREAD

**Issue by dave77777777** [smartlook/smartlook-mobile-issue-tracker#55]
**Platform**

Android

**Technology**

Native

**Smartlook SDK version**

The newest.

**Summary**

When users add a payment card in our app and is redirected to webView (Bank, 3DS), the record is stopped. So we do not see the webView and also what is happening after that (when user is redirected back to app).

We used this to unregister webView from blacklist:
Smartlook.setup("...");
Smartlook.unregisterBlacklistedClass(WebView.class);

We start recording in specific moment when the payment is needed.
if(!Smartlook.isRecording()) {
    Log.i("Smartlook", "becomeDriver-startRecording");
    Smartlook.startRecording();
}

**Comment by SenNeonoveNoci** [comment]
Hello @dave77777777,

You snippet:
`Smartlook.unregisterBlacklistedClass(WebView.class);`
Looks OK and should work fine, the problem might be elsewhere. So I understand the situation better, I have a few questions.
- The payment is happening in a `WebView` within the context of your application? Or the is a redirect to browser app?
- You setup Smartlook in your `Application` class but you are starting it before the payment?
- By not recorded you mean black/black recording or no recording of payment whatsoever?

**Comment by dave77777777** [comment]
Hello,

The application is using Braintree for payments with 3D Secure (3DS). So as far as I know the WebView is within the application context.

Yes, we do setup Smartlook in Application - OnCreate(). The recording starts just before startActivityForResult which starts BraintreeActivity.

The record is cut when WebView is opended and that is the end of the video.

**Comment by SenNeonoveNoci** [comment]
@dave77777777 Can you please fo a test sake record other parts of your application so you can verify its a Braintree `Activity`/`WebView` issue? If this is a case I'm gonna investigate further.

**Comment by dave77777777** [comment]
Unfortunately, we do not use webview in other parts of the application. But recording of other part of the app works well.

**Comment by SenNeonoveNoci** [comment]
@dave77777777 Would you mind adding some "basic" `WebView` to you application, just to test this?
Because I'm afraid there is some issue with Braintree actively blocking your recording, but it will be really time-consuming to test this, so I would rather test the other possibilities first.

**Comment by dave77777777** [comment]
Hello, we have tested the other webView (Google page) and it was recored well.

**Comment by dave77777777** [comment]
If you want, I can send the link to video in private message.

**Comment by dave77777777** [comment]
Hello, is there anything how we can help more with the issue?

**Comment by SenNeonoveNoci** [comment]
Sorry for the late response @dave77777777. Are you sure that brain tree activity uses `WebView` instance? 

There are a few possible solutions:
- You need to know for sure the `Class` of `View` that Braintree uses to display the content. And then use it in `unregisterBlacklistedClass()`.
- You can try to enable experimental SDK recording, this will record all surfaces in the application.
```
Smartlook.SetupOptionsBuilder builder = new Smartlook.SetupOptionsBuilder(@NotNull String apiKey)
        .setExperimental(boolean experimental);
```

I'm gonna test this myself with Braintree, if they have some sort of demo account. There is a possibility, they are blocking our recording due to security reasons.

**Comment by dave77777777** [comment]
Hello, we have tried experimental SDK recording, but we still do not see the webview. The time, when webview is loaded, recording is stopped and we do not see anything after user comes back from the webView.
