### ISSUE TITLE
Application crash turns in ANR

### ISSUE THREAD

**Issue by nacho007** [smartlook/smartlook-mobile-issue-tracker#56]
**Platform**

Android

**Technology**

Kotlin

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

implementation('com.smartlook.recording:app:1.7.0-native')

**Summary**

When forcing a crash, if Smartlook is started either with setup or setupAndStartRecording, the crash always turns in ANR.
When smartlook is not inited, the crash is thrown inmediatelly.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
Hello @nacho007,

are you using any crash reporting SDK in your application (like Firebase crashlytics, ...)? If so, there might be a "clash" between Smartlook SDK and the other library. This can be solved by calling:

```java
Smartlook.SetupOptionsBuilder builder = new Smartlook.SetupOptionsBuilder("YOUR_API_KEY")
        .setCrashTrackingMode(CrashTrackingMode.DISABLE);
Smartlook.setupAndStartRecording(builder.build());
```

This will disable Smartlook SDK crash/ANR tracking. If this does not fix the issue we will investigate further.

**Comment by nacho007** [comment]
Thank you very much! it solved the problem!
