### ISSUE TITLE
Use mavenCentral repository

### ISSUE THREAD

**Issue by drdla49** [smartlook/smartlook-mobile-issue-tracker#57]
**Platform**
Android

**Technology**
native

**Summary**
Can you please go to some of the large artifact repositories, eg maven central? Compared to your repository, there will be better security, availability, etc. Thank you

**Comment by SenNeonoveNoci** [comment]
Hi, @drdla49 we have this on our roadmap and will discuss this in Q1. Sadly I don't have any more info for you now, but give me your email and we will keep you updated.

**Comment by SenNeonoveNoci** [comment]
This will be addressed in the next release.
