### ISSUE TITLE
iOS - App crash in iPad4 after launch

### ISSUE THREAD

**Issue by tiggem1993** [smartlook/smartlook-mobile-issue-tracker#58]
**Platform**
iOS 10.3.3 (14G60) - iPad4

**Technology**
1. react-native 
2. @react-native-firebase
3. clevertap-react-native

**Build instructions [optional]**
1. react-native: "0.63.4"
2. @react-native-firebase/analytics: "^10.1.0",
3. @react-native-firebase/app: "^10.1.0",
4. @react-native-firebase/crashlytics: "^10.1.0",
5. clevertap-react-native: "^0.4.4",
6. react-native-webview: "^8.0.6",
7. react-navigation: "^4.0.10",
8. react-navigation-drawer: "^2.3.3",
9. react-navigation-stack: "^2.0.16",

**Affected devices [optional]**
iOS 10.3.3 (14G60) - iPad4

**Smartlook SDK version**
smartlook-react-native-wrapper: "^0.31.0"

**Summary**
This issue occurred only once to my user. I have come to know from my Firebase Crashlytics logs. Even I have also tried to find its video in Smartlook Account but didn't find any recording on that date and time. Its "Orientation" was "Portrait", Free RAM 44.71 MB & Free space 4.75 GB. I am not doing any king of recording in my App but still showing some recording related logs. I have marked recording line in attached screenshot with Suspicious line (2nd Screenshot).

**Steps to reproduce [optional]**
No such specific steps to reproduce this crash.

**Example Project [optional]**
Soory, due to company policy I can't share with you.

**Relevant logs and/or screenshots**
![FirebaseCrashlytics1](https://user-images.githubusercontent.com/16758184/106459674-36bc4400-64b8-11eb-92e4-957257c25a2f.jpg)
![FirebaseCrashlytics2](https://user-images.githubusercontent.com/16758184/106459684-3c198e80-64b8-11eb-9ef5-b76fdf8aa51a.jpg)
![FirebaseCrashlytics3](https://user-images.githubusercontent.com/16758184/106459696-40de4280-64b8-11eb-8268-9ba0e7a2be4d.jpg)
![FirebaseCrashlytics4](https://user-images.githubusercontent.com/16758184/106459705-450a6000-64b8-11eb-87f8-84e1eee144e0.jpg)
![FirebaseCrashlytics5](https://user-images.githubusercontent.com/16758184/106459712-476cba00-64b8-11eb-8ed1-ae7e4bd9a71b.jpg)
![FirebaseCrashlytics6](https://user-images.githubusercontent.com/16758184/106459723-4a67aa80-64b8-11eb-9081-f0cb1a0e944f.jpg)
![FirebaseCrashlytics7](https://user-images.githubusercontent.com/16758184/106459730-4dfb3180-64b8-11eb-8991-42a126c68399.jpg)
![FirebaseCrashlytics8](https://user-images.githubusercontent.com/16758184/106459738-50f62200-64b8-11eb-8956-32c76f12697f.jpg)
![FirebaseCrashlytics9](https://user-images.githubusercontent.com/16758184/106459748-53587c00-64b8-11eb-8823-1280b73b0f1c.jpg)

**Comment by pavel-kroh-smartlook** [comment]
Hi @tiggem1993 , thanks for the very detailed report! It looks like some corrupted data causing, could you please sent us the full crash report of the part where the suspicious line is? Thanks.

**Comment by tiggem1993** [comment]
> Hi @tiggem1993 , thanks for the very detailed report! It looks like some corrupted data causing, could you please sent us the full crash report of the part where the suspicious line is? Thanks.

Hi @pavel-kroh-smartlook , I have mention my log where suspicious line is present. Due to company policy I have just replace the word with "MYAPP" with my company app name.

**Crashed: com.apple.root.default-qos**
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000

```
Crashed: com.apple.root.default-qos
0  libobjc.A.dylib                0x1c218dd6 objc_msgSend + 21
1  Foundation                     0x1d945627 <redacted> + 80
2  Foundation                     0x1d9476e9 <redacted> + 196
3  CoreFoundation                 0x1ce98ebb __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 100
4  CoreFoundation                 0x1ce98db1 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 134
5  Foundation                     0x1d946f5f <redacted> + 450
6  Foundation                     0x1d94579b <redacted> + 452
7  Foundation                     0x1d947849 <redacted> + 104
8  CoreFoundation                 0x1cea7367 __53-[__NSArrayI enumerateObjectsWithOptions:usingBlock:]_block_invoke + 62
9  CoreFoundation                 0x1cea023d -[__NSArrayI enumerateObjectsWithOptions:usingBlock:] + 138
10 Foundation                     0x1d94721f <redacted> + 378
11 Foundation                     0x1d9457d5 <redacted> + 510
12 Foundation                     0x1d9476e9 <redacted> + 196
13 CoreFoundation                 0x1ce98ebb __65-[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:]_block_invoke + 100
14 CoreFoundation                 0x1ce98dc7 -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 156
15 Foundation                     0x1d946f5f <redacted> + 450
16 Foundation                     0x1d94579b <redacted> + 452
17 Foundation                     0x1d94559f <redacted> + 126
18 Foundation                     0x1d94641b <redacted> + 332
19 MYAPP	                  0x426a77 __60-[SLApiManager sendSessionRecordingSegment:completionBlock:]_block_invoke + 913956
20 libdispatch.dylib              0x1c651797 _dispatch_call_block_and_release + 10
21 libdispatch.dylib              0x1c65eb1d _dispatch_queue_override_invoke + 536
22 libdispatch.dylib              0x1c6601b5 _dispatch_root_queue_drain + 326
23 libdispatch.dylib              0x1c66000f _dispatch_worker_thread3 + 106
24 libsystem_pthread.dylib        0x1c80687d _pthread_wqthread + 1040
25 libsystem_pthread.dylib        0x1c80645c start_wqthread + 8
```

**Comment by pavel-kroh-smartlook** [comment]
Thanks a lot, very helpful!

**Comment by tiggem1993** [comment]
> Thanks a lot, very helpful!

Hi @pavel-kroh-smartlook , Is there any update?

**Comment by pavel-kroh-smartlook** [comment]
Hi @tiggem1993, I looked into it throughly yesterday afternoon and this morning. The apparent technical reason is that some data in our cache were corrupted. The iPad was probably offline the last time the app run, and with its new start Smartlook attempted to upload them, but it could not read the cache. I could not find any particular reason for the data corruption, and we are unable to reproduce the issue by emulating the expected behaviour. As it seems to be a solitary crash, we cannot do much much more about it now. We will monitor the presumable cause in testing to see if we can reproduce the issue (and fix it then) if future.

**Comment by arcsoft-chandresh** [comment]
Thanks @pavel-kroh-smartlook , I have also upgrade my Smartlook SDK version from 0.31.0 to 0.39.0 for avoiding future crashes. But still we are closely monitoring our Crashlytics. Hope it should crash again on same device. If occur then we will let you know with complete details.

**Comment by tiggem1993** [comment]
Hi @pavel-kroh-smartlook , Thanks for your details input. I have also upgraded my Smartlook SDK version from 0.31.0 to 0.39.0 for avoiding future crashes. Still we are closely monitoring our Firebase Crashlytics. Hope it will not crash again on same device. If occur then I will let you know with complete details.
