### ISSUE TITLE
Smartlook Android Unity SDK v1.6.2. AAR file cannot expand with error

### ISSUE THREAD

**Issue by cgao01** [smartlook/smartlook-mobile-issue-tracker#59]
I know this isn't directly related to the git code base, but I'm having an error 32 broken pipe message dialogue appear whenever I try to extract the AAR file downloaded from your guys' website:

https://smartlook.github.io/docs/sdk/unity?platform=android

If this isn't the place for this, please direct me to where I can bring this up to get resolved.  Thanks.

**Comment by cgao01** [comment]
Please disregard, it was an issue with my default archive tool.  I'm running MacOS Big Sur 11.1.  If anyone has the same issue, running with Unarchiver worked for me.

**Comment by SenNeonoveNoci** [comment]
@cgao01 Thanks for the heads up, hopefully, everything is gonna work for you fine.
