### ISSUE TITLE
Unity: android platform recording black screen 95% of the time?

### ISSUE THREAD

**Issue by DorsalFin** [smartlook/smartlook-mobile-issue-tracker#61]
**Platform**
Android

**Technology**
Unity

**Build instructions [optional]**
Unity version 2018.4

**Rendering [optional]**
OpenGL

**Smartlook SDK version**
1.4.2 and 1.6.2

**Summary**
When viewing the recordings approximately 95% of them are just black screens. Can still see the gestures overlayed on top. Can't seem to find any pattern with the working ones.

**Relevant logs and/or screenshots**
We're simply calling SetupAndStartRecording on app open.

**Comment by DorsalFin** [comment]
I have some more info on this... excluding recording any device with 'Google' in the name seems to remove all the black screens.

**Comment by adamblack** [comment]
Hi @DorsalFin ,

currently there is a limitation for Unity, video is recorded only for API 24+, otherwise there is a black screen. Maybe that is the issue? You can check version of Android in the left menu while playing recordings.
