### ISSUE TITLE
Cordova iOS unknown receiver WKWebView

### ISSUE THREAD

**Issue by harangusdan** [smartlook/smartlook-mobile-issue-tracker#64]
**Platform**
iOS

**Technology**
Ionic (Cordova)

**Build instructions [optional]**
@ionic/cli - 6.12.4
cordova-ios - 6.2.0
cordova - 10.0.0
cordova-plugin-smartlook - 1.7.3

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**
1.7.3

**Summary**
Ionic cordova iOS build fails with error 65 due to a CompileC error on `SmartlookPlugin.m`. By building the application directly on XCode, the following error occurred: "Unknown receiver 'WKWebView'; did you mean 'UIWebView'?". It seems that the WKWebView is not imported at all. By adding the `#import <WebKit/WebKit.h>`, the build was successful.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**
<img width="1006" alt="Screenshot 2021-02-17 at 11 37 42" src="https://user-images.githubusercontent.com/55430168/108186741-699c4400-7116-11eb-8084-9714af70b625.png">

**Comment by pavel-kroh-smartlook** [comment]
Smartlook's Cordova plugin updated to 1.7.4 that fixes this issue.
