### ISSUE TITLE
iOS Recordings appear as Active in admin dashboard but no recording data is logged.

### ISSUE THREAD

**Issue by Will-Virti** [smartlook/smartlook-mobile-issue-tracker#66]
**Platform**
iOS 7 Android
**Technology**
Unity

**Build instructions [optional]**
Unity iOS Build (Cloud Build Service)

**Rendering [optional]**
Metal

**Affected devices [optional]**
All iOS Devices

**Smartlook SDK version**
Release 165
app-1.6.2-unity(Android build app)
**Summary**
Smartlook sessions are active in the admin dashboard. No data is being recorded on iOS devices. The same project built for Android works fine and recordings appear in Smartlook using the same setup.

**Steps to reproduce [optional]**
Launch App on iOS with Smartlook setup following the documentation outlined on the Smartlook setup.

**Comment by jCharv** [comment]
@Will-Virti Hey, could you please specify what version of Unity you are using? Thank you.

**Comment by Will-Virti** [comment]
2019.4(LTS) we build on 2019.4.8f1 as well as the latest LTS build which is 2019.5.21f1 (LTS)

**Comment by jCharv** [comment]
@Will-Virti Unfortunately I haven't been able to reproduce that issue (2019.4 LTS). Maybe you could share the part of your code where you initialize Smartlook and start recording? Or even better, some example unity project where those recordings fail to show in the dashboard? Atm I have no idea what might be the issue.

**Comment by pavel-kroh-smartlook** [comment]
Stalled issue. Closing.
