### ISSUE TITLE
unregisterBlacklistedView not working on Android

### ISSUE THREAD

**Issue by dark-TON** [smartlook/smartlook-mobile-issue-tracker#67]
**Platform**
Android

**Technology**
React native

**Build instructions [optional]**
"react-native": "0.63.4"
target SDK version is 29

gradle.properties
android.useAndroidX=true
android.enableJetifier=true

gradle version: com.android.tools.build:gradle:4.0.1

Using gradle-6.5-all.zip in gradle-wrapper.properties.

**Smartlook SDK version**
Tried following combinations:
smartlook-react-native-wrapper: 0.26.0 and android sdk 1.4.0
smartlook-react-native-wrapper: 0.39.0 and android sdk 1.6.3 / 1.7.0

**Summary**
Not able to show input field values in screen recording. They are always blacked out.
Using react native TextInput. This does work on iOS devices, but not on Android.
No errors found. Everything working except whitelisting input fields.

Should setRenderingMode to 'native' allow visibility of field values? Tried that also but no luck.

`<TextInput 
      ref={(ref) => {
           Smartlook.unregisterBlacklistedView(ref);
      }
}`

**Comment by adamblack** [comment]
Hi @dark-TON  ,

we found the issue. Not sure if it is still somehow important to you but we are going to do new release soon.

**Comment by dark-TON** [comment]
Hey @adamblack , 
thanks for the info, pretty important to us, we are waiting for this fix.

Cheers

**Comment by adamblack** [comment]
Hi @dark-TON ,

New version 0.40.0 is released, we also updated our docs. Please use new method, as shown in snippet:

```
<WebView
                ref={ (ref) => {
                    Smartlook.registerWhitelistedView(ref);
                  }
                }
                    source={{ uri: 'https://infinite.red' }}
                    style={{ marginTop: 20 }}
                />
```

                
Feel free to open new issue in case there is anything broken. I tested that on several 0.6x+ RN versions so it should be fine.

Thanks for reporting that!
