### ISSUE TITLE
Sensitive views are not hided, when a transparent view is above

### ISSUE THREAD

**Issue by iaminh** [smartlook/smartlook-mobile-issue-tracker#68]
**Platform**
iOS

**Technology**

Swift

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

1.7.1
**Summary**

Hiding sensitive views do not work if other view2 is presented on it and it has a transparent background.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/66557323/109096684-48db7c00-771e-11eb-990f-44dae70d6e76.png)

**Comment by pavel-kroh-smartlook** [comment]
Hi @iaminh , we are aware about issues in this area a work on a fix.

**Comment by pavel-kroh-smartlook** [comment]
Hi again @iaminh, after our morning standup we have an ETA for the fix: coding should be finished this week (the 1st week of March), testing and the release the next one.

**Comment by pavel-kroh-smartlook** [comment]
Hi @iaminh , yesterday, we released new version of iOS SDK 1.7.4 that addresses sensitive data issues https://smartlook.github.io/docs/sdk/sdk-release-changelogs?platform=ios#
