### ISSUE TITLE
Returning Visitors not showing in Dashboard

### ISSUE THREAD

**Issue by gkbpay** [smartlook/smartlook-mobile-issue-tracker#7]
**Platform**
Android

**Technology**
Native Kotlin

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**

**Summary**
While an existing user comes to app in the recording section of dashboard I am not seeing any user under Returning Visitors.
I want to know how this works and what is meant by returning visitors.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**

**Comment by SenNeonoveNoci** [comment]
Hi @gkbpay, please upgrade SDK to `implementation 'com.smartlook.recording:app:1.5.3-native'`. We had a bug in an SDK regarding your issue that is fixed in 1.5.3.
