### ISSUE TITLE
Smartlook.isRecording() return value

### ISSUE THREAD

**Issue by gwijaya94** [smartlook/smartlook-mobile-issue-tracker#72]
**Platform**
Android

**Technology**
React Native

**Build instructions [optional]**
`"react-native": "0.63.4",`

**Smartlook SDK version**
`"smartlook-react-native-wrapper": "^0.40.0",`

**Summary**
Expected return boolean from `Smartlook.isRecording()` 

**Steps to reproduce [optional]**
Applied `Smartlook.isRecording()` before and after `Smartlook.startRecording()`

**Relevant logs and/or screenshots**
**Code:**
![Screen Shot 2021-03-26 at 11 46 45](https://user-images.githubusercontent.com/65438712/112581088-f4b0de00-8e28-11eb-8c2b-f7d5e4c6c13b.png)

**Log:**
![Screen Shot 2021-03-26 at 11 47 06](https://user-images.githubusercontent.com/65438712/112581256-ff6b7300-8e28-11eb-8858-ce646ed03a16.png)

**Comment by adamblack** [comment]
Hi @gwijaya94 ,

isRecording is resolved via promise so you can use that variable via i.e.:

`Smartlook.isRecording().then( isRecording =>
        console.log(isRecording)
    )`
