### ISSUE TITLE
Cannot setup  User e-mail user property

### ISSUE THREAD

**Issue by alejandro-vori** [smartlook/smartlook-mobile-issue-tracker#74]
**Platform**
iOS, Swift

**Technology**
native

**Build instructions [optional]**
cocoapods

**Smartlook SDK version**
1.7.0

**Summary**
I'm trying to setup **User e-mail** but I can't seem to make it show up where's supposed on the dashboard

![Screenshot at Apr 05 15-35-09](https://user-images.githubusercontent.com/79858916/113631753-26932300-9627-11eb-9f47-98dd8fe658a3.png)

I was able to do `Smartlook.setSessionProperty(value: email, forName: "userEmail", options: .immutable)` as a workaround to make it appear as a custom user property but I really need to set it up as part of the **user information** group for better sorting in the dashboard. Please help!

**Comment by pavel-kroh-smartlook** [comment]
The method you use is no workaround, but the way to set the user email, the terminology is a bit confusing. When the name of the property is `email`, then it is shown among the user properties.

**Comment by alejandro-vori** [comment]
Thank you @pavel-kroh-smartlook !
