### ISSUE TITLE
Smartlook not updating app_version_name

### ISSUE THREAD

**Issue by craigwduckett** [smartlook/smartlook-mobile-issue-tracker#75]
**Platform**
Both

**Technology**
React native

**Smartlook SDK version**
0.40.0
**Summary**
Installed app version 2.4.8 then upgraded to 2.5.0 and the app_version_number on recordings doesn't update as per screen shot

**Steps to reproduce [optional]**
Install a lower version of an app on a device then check the recordings that the version numbers match then update the app to a higher version and the number on the recordings site doesn't change

**Relevant logs and/or screenshots**
![chrome_15gtYBA7I1](https://user-images.githubusercontent.com/7798937/114454552-d58abc80-9c2e-11eb-869f-f9aa03ee8c39.png)

**Comment by adamblack** [comment]
Hi @craigwduckett ,

this issue is already addressed however we also need to release new SDK version. I am not able to give you ETA right now (it is connected to other set of developed future features). However it will be solved for sure.

**Comment by craigwduckett** [comment]
@adamblack ok thanks for the update. We look forward to the new version.
