### ISSUE TITLE
iOS React Native on TestFlight: Sessions look active but don't get saved

### ISSUE THREAD

**Issue by WaterCityFlame** [smartlook/smartlook-mobile-issue-tracker#77]
**Platform**
Android, iOS (Issue is on iOS)

**Technology**
React Native 

**Build instructions [optional]**
react-native: ^0.61.5
`npx react-native bundle --dev false --entry-file index.js --bundle-output ios/main.jsbundle --platform ios --assets-dest ./`
then pod install
then Fastlane's `build_ios_app` function with `export_options` of `{ method: 'app-store'}`

**Affected devices [optional]**
iOS builds on Test Flight - our dev builds seem to be fine

**Smartlook SDK version**
smartlook-react-native-wrapper: 0.32.0
Smartlook SDK: 1.5.0

**Summary**
Smartlook appears to record testflight sessions - they show up under active sessions. 
Later, nothing is saved. 

**Steps to reproduce [optional]**

1. Make a react-native app with smartlook integrated
2. Upload it to TestFlight (iOS's beta testing platform)
3. Install TestFlight and the beta build on your test device
4. Do some things that smartlook should record (open the app, click buttons for 2 minutes or so)
       **Expected:** an active session is visible in the smartlook dashboard
       **Actual:** an active session is visible! Yes!
5. Wait half an hour or so without interacting with the app 
      **Expected:** Session disappears from active sessions and joins completed sessions
     **Actual:** It disappears from active sessions and is never seen again

I don't know if Smartlook works in full production app-store distribution with this set-up. It does work on release builds distributed internally

**Comment by pavel-kroh-smartlook** [comment]
Hi, 

both the react native plugin and native Smartlook SDK are a bit outdated, current version of the plugin is 0.39, native iOS SDK is 1.7.5. Where did you get them from (I expect that recently, as you only test them in the app)? Is it possible to update them to latest version?

To the issue itself: it looks like Smartlook is initialised (hence the "active session") but never actually start recording (thus nothing is uploaded). 

Could you share a code snippet with the Smartlook initialisation in your code?

**Comment by WaterCityFlame** [comment]
Hi @pavel-kroh-smartlook Sorry for taking like a week to get back to you. 

1. Upgrading the SDKs seems to have worked so that's embarrassing. For future googlers though: if you expect it to work through test flight, keep it up to date
2. code is this: 
```
    if (Javelin.global().env.SMART_LOOK_API_KEY.length) {
      Smartlook.setupAndStartRecording(Javelin.global().env.SMART_LOOK_API_KEY);
      Smartlook.enableCrashlytics(true);
    }
```
Javelin is a library we built internally for a bunch of business logic, and it also wraps our environment variables. I am sure that it has an API key, because the app got as far as showing an "Active Session" in SmartLook. 

I'm going to do a bit more testing internally and report back, but this looks for now like it's working

**Comment by pavel-kroh-smartlook** [comment]
Hi @WaterCityFlame, I'm glad to hear it works for you again! I'll close this issue now, if there is anything wrong, feel free to open a new dedicated one.
