### ISSUE TITLE
Getting Crash in iPhone 6s (12.4) when closing AVPlayerviewController

### ISSUE THREAD

**Issue by SKMaurya1992** [smartlook/smartlook-mobile-issue-tracker#79]
**Platform**
iOS

**Technology**
Swift

**Build instructions [optional]**
  pod 'Smartlook'

**Rendering [optional]**

**Affected devices [optional]**
iPhone 6s (12.4)

**Smartlook SDK version**
(1.7.5)

**Summary**
Application getting crashed while closing the AVPlayerViewController in Landscape mode.

**Steps to reproduce [optional]**
We are using "XCDYouTubeKit" to create and launch a youtube video. Install the above pod and use below code to launch AVPlayerViewController instance. Put the application in landscape mode and press on close button.

extension UIViewController {
    func openYouTubeVideo(videoID: String) {
        let videoPlayerVC = AVPlayerViewController()
        present(videoPlayerVC, animated: true, completion: nil)

        XCDYouTubeClient.default().getVideoWithIdentifier(videoID) { [weak self] video, _ in
            guard let weakSelf = self else {
                return
            }
            if let playerVideo = video, let streamURL = playerVideo.streamURL {
                videoPlayerVC.player = AVPlayer(url: streamURL)
                videoPlayerVC.player?.play()
            } else {
                weakSelf.dismiss(animated: true, completion: nil)
            }
        }
    }
}

**Example Project [optional]**

**Relevant logs and/or screenshots**
2021-04-28 13:19:11.117540+0530 Studi QA[12846:216532] -[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x600000290c60
2021-04-28 13:19:11.127219+0530 Studi QA[12846:216532] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteValue doubleValue]: unrecognized selector sent to instance 0x600000290c60'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112b9e8db __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000111fcdac5 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112bbcc94 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000112ba3623 ___forwarding___ + 1443
	4   CoreFoundation                      0x0000000112ba5418 _CF_forwarding_prep_0 + 120
	5   QuartzCore                          0x0000000110b87071 -[NSNumber(CAAnimatableValue) CA_interpolateValue:byFraction:] + 55
	6   QuartzCore                          0x0000000110b83acf -[CABasicAnimation applyForTime:presentationObject:modelObject:] + 650
	7   QuartzCore                          0x0000000110b513fe _ZN2CA5Layer18presentation_layerEPNS_11TransactionE + 492
	8   Studi QA                            0x000000010a3ecd64 -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 187
	9   Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	10  Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	11  Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	12  Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	13  Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	14  Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	15  Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	16  Studi QA                            0x000000010a3ed4ac -[SLNativeSnapshotRenderer nativeOverlayForViewLayer:parentOverlay:overlayDict:] + 2051
	17  Studi QA                            0x000000010a3eae74 -[SLNativeSnapshotRenderer takeSnapshotWithScreenWireframe:completion:] + 728
	18  Studi QA                            0x000000010a3e497b __43-[Smartlook takeScreenSnapshotWithVCClass:]_block_invoke + 108
	19  Studi QA                            0x000000010a406870 __70-[SLSceenWireframeCallbackOperation initWithScreenWireframe:callback:]_block_invoke + 77
	20  Foundation                          0x000000010e72533e __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	21  Foundation                          0x000000010e725246 -[NSBlockOperation main] + 68
	22  Foundation                          0x000000010e722120 -[__NSOperationInternal _start:] + 688
	23  Foundation                          0x000000010e727e87 __NSOQSchedule_f + 227
	24  libdispatch.dylib                   0x00000001148f1d7f _dispatch_call_block_and_release + 12
	25  libdispatch.dylib                   0x00000001148f2db5 _dispatch_client_callout + 8
	26  libdispatch.dylib                   0x0000000114900080 _dispatch_main_queue_callback_4CF + 1540
	27  CoreFoundation                      0x0000000112b05a79 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	28  CoreFoundation                      0x0000000112b00126 __CFRunLoopRun + 2310
	29  CoreFoundation                      0x0000000112aff4d2 CFRunLoopRunSpecific + 626
	30  GraphicsServices                    0x00000001167652fe GSEventRunModal + 65
	31  UIKitCore                           0x000000011db03fc2 UIApplicationMain + 140
	32  Studi QA                            0x00000001095e685b main + 75
	33  libdyld.dylib                       0x0000000114967541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by pavel-kroh-smartlook** [comment]
Hi @SKMaurya1992 , thanks for your detailed report!

Could you confirm this happens only on a specific version of iOS? 

The issue is probably caused by an improperly attributed animation on a, probably `AVPlayerViewController` related, view. Smartlook touches the `presentationLayer` of the affected system view in order to detect if there is an animation on it, which ad-hoc instantiates the animation and causes the crash because its attributes are not of an expected class. See e.g., [this discussion](https://stackoverflow.com/questions/9980279/monotouch-nsconcretevalue-doublevalue-unrecognized-selector-sent-to-instanc).

We will look into it in more details to think about possible workarounds.

**Comment by SKMaurya1992** [comment]
This issue is only happening for iOS 12 version specifically on landscape mode only. For portrait mode it's working as expected.

**Comment by pavel-kroh-smartlook** [comment]
Thanks for clarification. We try to find a way to avoid these crashes.

**Comment by pavel-kroh-smartlook** [comment]
Hi, unfortunately we are unable to reproduce the issue so far, we plan to revisit it again i few days. Would it be possible to provide us with a minimal example app that crashes under the circumstances? Thanks.

**Comment by SKMaurya1992** [comment]
[testProject.zip](https://github.com/smartlook/smartlook-mobile-issue-tracker/files/6420262/testProject.zip)


hi @pavel-kroh-smartlook , Please find the attached test project. i think it's happening because of implementation of below method in AppDelegate. We need this since we have to restrict user to portrait on some screen.

    func application(_: UIApplication, supportedInterfaceOrientationsFor _: UIWindow?) -> UIInterfaceOrientationMask

**Comment by pavel-kroh-smartlook** [comment]
Thanks! cc: @vaclav-halik-smartlook

**Comment by V1992** [comment]
issue still present after updated with latest version

**Comment by pavel-kroh-smartlook** [comment]
Damn… thanks for reporting, this is not exactly the original issue, but something very close, it seems that the video player is full of unpleasant surprises. @jCharv is working on it.

**Comment by roimulia2** [comment]
Should we avoid adding SmartLook for AVPlayer based apps for now?
