### ISSUE TITLE
Crashes caused by Smartlook SDK

### ISSUE THREAD

**Issue by eareyereading** [smartlook/smartlook-mobile-issue-tracker#8]
**Platform**
iOS

**Technology**
native

**Smartlook SDK version**
1.4.1

**Summary**
Many crashes like this happened in our app.

0 libobjc.A.dylib objc_retain + 16
1 BookReaderApp SLChangesDetector.m - Line 372 ____smartlook_ca_layer_add_animation_for_key_method_block_invoke + 372
2 libdispatch.dylib _dispatch_call_block_and_release + 24

**Relevant logs and/or screenshots**
<img width="720" alt="Screen Shot 2020-09-11 at 4 56 12 PM" src="https://user-images.githubusercontent.com/65410804/92898670-c2bdc880-f450-11ea-8733-2210e27b5704.png">

**Comment by pavel-kroh-smartlook** [comment]
Hi @eareyereading , looking into it, however the line were the code crashes reads `NSMutableArray *log = [NSMutableArray new];` - not something one would expect being unsafe. Is there an obvious pattern in iOS or Smartlook SDK version when it happens?

**Comment by eareyereading** [comment]
From the crash logs collected by Crashlytics, we see that the crashes occur only on iOS 12 and iOS 11, not on iOS 13. The Smartlook SDK is the latest version.

**Comment by pavel-kroh-smartlook** [comment]
Thanks a lot for the additional info.

**Comment by pavel-kroh-smartlook** [comment]
Hi again, we could not reproduce it on the in the respective iOS version simulators. We will examine the related code in the SDK and try to find possible cause and refactor it to be safer for the upcomming SDK version.

**Comment by pavel-kroh-smartlook** [comment]
Hi, the new version 1.5.0 that we just released tries to work around this issue. However, as we could not reproduce it, we cannot be 100% sure it is fixed.

**Comment by pavel-kroh-smartlook** [comment]
The issue is closed due to inactivity.
