### ISSUE TITLE
Wrong argument name causes java.lang.NullPointerException

### ISSUE THREAD

**Issue by SedlarDavid** [smartlook/smartlook-mobile-issue-tracker#81]
**Platform**
Android

**Technology**
Flutter

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**

**Smartlook SDK version**
  smartlook: ^2.0.0

**Summary**
In the smartlook.dart, there is method that invokes platform method for set rendering mode. Index of wanted mode is passed down under key "renderingMode". In iOS platform files the argument key is right, but inside SmatlookPlugin.java, argument is withdrawn using call.argument("renderingMethod");. Since renderingMode != renderingMethod int is then null and causes exception.

**Steps to reproduce [optional]**

**Example Project [optional]**

**Relevant logs and/or screenshots**
![Screenshot 2021-05-14 at 14 04 10](https://user-images.githubusercontent.com/58554772/118268213-66b6b280-b4bd-11eb-87d0-fcc74d936022.png)
![Screenshot 2021-05-14 at 14 04 25](https://user-images.githubusercontent.com/58554772/118268214-674f4900-b4bd-11eb-9ef3-93d705a0ace0.png)

Please look at this issue since it is then impossible to set different rendering mode on android and prevent from recording sensitive user data.

**Comment by adamblack** [comment]
Hi @SedlarDavid ,

thank you for pointing that out! New version should be already on pub.dev.
