### ISSUE TITLE
Smartlook failing to group sessions with the same identifier together as the same visitor

### ISSUE THREAD

**Issue by AndrewMorsillo** [smartlook/smartlook-mobile-issue-tracker#84]
**Platform**
React native Android and iOS

**Technology**
react-native

**Build instructions [optional]**
"react-native": "0.64.1",

**Affected devices [optional]**
Any

**Smartlook SDK version**
 "smartlook-react-native-wrapper": "^0.40.0"

**Summary**
Smartlook is counting the same user on the same device identified with the same userId and same email address as multiple different visitors.

I believe this is the same as https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/4 which was closed with a fix but it doesn't seem to have resolved the issue.

I suspect this may be an interaction between the Smartlook SDK and AppCenter codepush. We use [react-native-code-push](https://github.com/microsoft/react-native-code-push) to apply over the air updates to our react native JS code. 

When a codepush is applied the JS code is entirely unloaded and restarted which results in calling the Smartlook initialization and user identification functions again. When watching Smartlook recordings the codepush process doesn't always seem to interrupt the recording. I can see the app reload in the recording with an event titled "MainActivity". It seems that the sessions where a codepush is applied could be the sessions which result in these duplicate visitors.

This issue is greatly impacting our ability to use Smartlook for analytics since users are marked as dropping off points in a funnel when in reality they continue their journey but are counted as a separate (duplicated) visitor. This throws off all of the counts and session recordings and makes it difficult/impossible to follow a user's journey.

Smartlook should strictly count identical userIds and emails as the same visitor no matter what.

**Steps to reproduce [optional]**
Unsure, but possibly:

1. Start a react native app with Smartlook and react-native-codepush
2. Allow a codepush bundle to be applied to the running app while smartlook is recording
3. See two separate visitors in smartlook despite the same id, email, and device (possibly only upon the _next_ session of the user)

Again I am unsure if codepush is truly the source of this issue but it seems like a possibility. Either way I think it would be better if Smartlook _always_ counted the same id/email as the same visitor.

**Comment by krystofcelba** [comment]
Hey, we've recently released a new version `1.2.1`, where all the issues should be fixed. Please do the update and in case of any issue let us know. Thanks!
