### ISSUE TITLE
When I add it to the project, it all logs. **No package ID 24 found for ID 0x245a3c5c**

### ISSUE THREAD

**Issue by mahanpyk** [smartlook/smartlook-mobile-issue-tracker#85]
**Platform**
android

**Technology**
flutter

**Build instructions [optional]**
flutter version 2.2.1
gradle 4.2.1
kotlin-gradle-plugin 1.5.10

**Smartlook SDK version**
  smartlook: ^2.0.1

**Summary**
The library is working properly but is constantly logging in this line of code
E / <package name> (17131): No package ID 24 found for ID 0x245a3c5c.

**Relevant logs and/or screenshots**
![image](https://user-images.githubusercontent.com/45437882/120372014-e51fab00-c32b-11eb-8193-5885d1c70922.png)

**Comment by adamblack** [comment]
Hi @mahanpyk ,

thank you for reporting that. We will look into that.
