### ISSUE TITLE
SLApiManager EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by jtouzy** [smartlook/smartlook-mobile-issue-tracker#86]
**Platform**
iOS.

**Technology**
Native.

**Build instructions [optional]**
App build with Xcode 12.5.

**Rendering [optional]**
N/A

**Affected devices [optional]**
N/A

**Smartlook SDK version**
1.7.5

**Summary**
Sometimes, a crash is reported in our Crashlytics console.
It's not happening really often, but it needs some investigation.
I think it might be a threading problem internally.

**Steps to reproduce [optional]**
N/A

**Example Project [optional]**
N/A

**Relevant logs and/or screenshots**
<img width="941" alt="Screenshot 2021-06-10 at 08 02 33" src="https://user-images.githubusercontent.com/5709133/121473634-44805980-c9c3-11eb-8d8a-2fb375c5916e.png">

**Comment by pavel-kroh-smartlook** [comment]
Hi @jtouzy , thanks for the report, we will sure look into it.

**Comment by jCharv** [comment]
@jtouzy Hey, we found the bug, an update will follow shortly. Thank you for your great feedback!

**Comment by pavel-kroh-smartlook** [comment]
Hi @jtouzy , the fix is finally out in our [1.7.10](https://docs.smartlook.com/docs/sdk/sdk-release-changelogs?platform=ios#) version. Thanks for the patience.
