### ISSUE TITLE
Wrong path to package.json from smartlook-react-native-wrapper/lib/module/Smartlook.js

### ISSUE THREAD

**Issue by Cosmitar** [smartlook/smartlook-mobile-issue-tracker#88]
**Platform**
both

**Technology**
React native

**Build instructions [optional]**
react-native@0.61.5
smartlook-react-native-wrapper@1.1.1

**Rendering [optional]**

**Affected devices [optional]**
build on development

**Smartlook SDK version**
smartlook-react-native-wrapper@1.1.1

**Summary**
I'm updating from Smartlook v0.28.0, since my project has not typescript I got an error (Namespace not marked type-only declare) into node_modules/smartlook-react-native-wrapper/src/Smartlook.ts.
To avoid implementing Typescript in the project I decided to include Smartlook from `smartlook-react-native-wrapper/lib/module` and the error is 
```
error: bundling failed: Error: Unable to resolve module `../package.json` from `node_modules/smartlook-react-native-wrapper/lib/module/Smartlook.js`
```
I fixed it by changing relative path from `/node_modules/smartlook-react-native-wrapper/lib/module/Smartlook.js:7`
```
--- a/node_modules/smartlook-react-native-wrapper/lib/module/Smartlook.js
+++ b/node_modules/smartlook-react-native-wrapper/lib/module/Smartlook.js
@@ -4,7 +4,7 @@ const SmartlookBridge = NativeModules.RNSmartlook;
 
 const REACT_NATIVE_VERSION = require('react-native/package.json').version;
 
-const SMARTLOOK_VERSION = require('../package.json').version;
+const SMARTLOOK_VERSION = require('../../package.json').version;
 
 const REF_NOT_INITIALIZED_ERROR = "The ref hasn't been initialized yet. This might happen if it is not mounted, or if it hasn't finished mounting.";
```
**Steps to reproduce [optional]**
- create a React Native project with no typescript.
- install smartlook-react-native-wrapper.
- include Smartlook from module subfolder `import Smartlook from 'smartlook-react-native-wrapper/lib/module';`
- build
- see Metro bundle log displaying the mentioned error.

**Example Project [optional]**

**Relevant logs and/or screenshots**
```
error: bundling failed: Error: Unable to resolve module `../package.json` from `node_modules/smartlook-react-native-wrapper/lib/module/Smartlook.js`:

None of these files exist:
  * package.json
  * node_modules/smartlook-react-native-wrapper/lib/package.json/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
 ```

**Comment by krystofcelba** [comment]
Hey, sorry for waiting. We are going to release a new version after the weekend with the fix. I will inform you about that.

**Comment by Cosmitar** [comment]
Awesome, I'm currently addressing it with patch-package.
Thanks and great job you're doing at Smartlook!!

**Comment by krystofcelba** [comment]
Thanks for your kind words! FYI: The version 1.2.0 was released with fix for the package.json path issue among other things so please update 👍.
