### ISSUE TITLE
enablecrashlytics not found in 1.2.0 version (android)

### ISSUE THREAD

**Issue by sahilmahajanpikup** [smartlook/smartlook-mobile-issue-tracker#90]
**Platform**
Android,ios

**Technology**
react native

**Affected devices [optional]**
android only

**Smartlook SDK version**
smartlook-wrapper version 1.2.0

**Summary**
when upgrade to latest version of react-native-smartlook-wrapper got enableAnalytics not found error on android

**Relevant logs and/or screenshots**
![Screenshot (29)](https://user-images.githubusercontent.com/84334816/125641834-cf8dd104-e7b0-4fe9-9852-2e7fc7b8bb05.png)

**Comment by krystofcelba** [comment]
Hey, thanks for your bug report! I'm going to investigate it and let you know with a solution.

Krystof Celba
Smartlook

**Comment by krystofcelba** [comment]
Please try to run this command `rm -r  ~/.gradle/caches/modules-2/files-2.1/com.smartlook.recording/` and run the build again. (It should remove the possible cached old version of the native android sdk.) @sahilmahajanpikup

**Comment by sahilmahajanpikup** [comment]
no success

**Comment by krystofcelba** [comment]
We've just released fixed version `1.2.1`. Please try it and let us know. Thanks! @sahilmahajanpikup

**Comment by sahilmahajanpikup** [comment]
build success thanks
