### ISSUE TITLE
Bugsnag Smartlook connection

### ISSUE THREAD

**Issue by AmirDoreh** [smartlook/smartlook-mobile-issue-tracker#91]
i am using smartlook-react-native-wrapper and bugsnag/bugsnag-react-native
i wonder how can i connect them to see the session from bugsnag also?

<img width="1422" alt="Screen Shot 2021-07-14 at 8 21 50 PM" src="https://user-images.githubusercontent.com/45465967/125666661-0ac2efb3-5874-4a3a-a053-7c98ec7bad7c.png">

**Comment by krystofcelba** [comment]
Hi @AmirDoreh,
according to your question, you use Smartlook with React Native, where we currently don't support automatic Bugsnag integration. But you should be able to set up it manually this way:

```
Smartlook.registerIntegrationListener(
  (dashboardSessionUrl: string) => {
    Bugsnag.addOnError((event) => {
      event.addMetadata("Smartlook", {
        "Smartlook session dashboard URL": dashboardSessionUrl,
      });
      return true;
    });
  },
  (_dashboardVisitorUrl: string) => {}
);
```
