### ISSUE TITLE
Blacklisting continues even after Webview returns control to the app

### ISSUE THREAD

**Issue by dnvarun** [smartlook/smartlook-mobile-issue-tracker#94]
**Platform**
android

**Technology**
react native

**Build instructions [optional]**
- smartlook-react-native-wrapper 1.1.1
- react-native 0.63.2

**Rendering [optional]**
N/A

**Affected devices [optional]**
All

**Smartlook SDK version**
smartlook-react-native-wrapper 1.1.1

**Summary**
From the past few weeks, we have been seeing unnecessary blacklisting across the screens. We are using react native sdk on android. We are using a 3rd party SDK https://github.com/plaid/react-native-plaid-link-sdk/ which I think opens a webview which gets blocked completely by a full screen striped overlay. This is understandable from the docs. But even after the control returns to our app, the full screen blocker remains, essentially making smartlook useless after this.

**Steps to reproduce [optional]**
N/A

**Example Project [optional]**
N/A

**Relevant logs and/or screenshots**
N/A

**Comment by SenNeonoveNoci** [comment]
Hello, @dnvarun our React Native developer @krystofcelba is looking into this and will write a follow up shortly.

**Comment by dnvarun** [comment]
Anything on this? I have already mailed support@smartlook.com 15 days back regarding this, but there is no resolution till now

**Comment by dnvarun** [comment]
Hey krystof , I have replied to you via email few days back. Any luck from that?

**Comment by krystofcelba** [comment]
Hey Varun,
I have contacted you on the intercom. Let's continue there. Thanks
