### ISSUE TITLE
Several crashes after adding SmartLook SDK

### ISSUE THREAD

**Issue by mohdFathi** [smartlook/smartlook-mobile-issue-tracker#96]
**Platform**
Android

**Technology**
Native Android

**Affected devices [optional]**
will mention some of them for each crash separately below

**Smartlook SDK version**
1.8.3-native

**Summary**
I am getting crashes reported in Crashlytics after adding SmartLook SDK to android. will mention the stacktraces below.

**Steps to reproduce [optional]**
unable to reproduce.no particular pattern

**Relevant logs and/or screenshots**
# Crash 1 : -
_________________________________
Caused by java.lang.NullPointerException
Attempt to read from field 'long p.a.b.a.f.r.n.c' on a null object reference
a.a.b.a.f.r.n.a (n.java:2)
a.a.b.a.c.n.a.a (a.java:115)
a.a.b.a.c.l.c.l (c.java:11)
a.a.b.a.c.l.c.h (c.java:1)
a.a.b.a.c.l.c$g.b (c.java:11)
a.a.b.a.c.h.d$g.a (d.java:3)
a.a.b.a.c.h.d$g.invoke (d.java:1)
a.a.b.a.c.h.c.a (c.java:200)
a.a.b.a.c.h.c.a (c.java:3)
a.a.b.a.c.h.d.c (d.java:12)
a.a.b.a.c.h.d.a (d.java:483)
a.a.b.a.c.h.d.a (d.java:1)
a.a.b.a.c.h.d$j.onActivityStopped (d.java:14)
android.app.Application.dispatchActivityStopped (Application.java:496)
androidx.appcompat.app.AppCompatActivity.onStop (AppCompatActivity.java:216)
android.MainActivity.onStop (MainActivity.java:310)
android.app.Instrumentation.callActivityOnStop (Instrumentation.java:1473)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:980)

* Sample Devices where the above crash occurred :

Brand:INFINIX MOBILITY LIMITED
Model:Infinix NOTE 5
Orientation: Portrait
RAM free: 793.58 MB
Disk free: 3.21 GB
Version:10
Orientation: Portrait
_____________________________________________________________
# Crash 2 : -

Fatal Exception: java.lang.RuntimeException
Could not read input channel file descriptors from parcel.
android.view.InputChannel.nativeReadFromParcel (InputChannel.java)
android.view.InputChannel.readFromParcel (InputChannel.java:148)
android.view.InputChannel$1.createFromParcel (InputChannel.java:39)
android.view.InputChannel$1.createFromParcel (InputChannel.java:37)
com.android.internal.view.InputBindResult.<init> (InputBindResult.java:68)
com.android.internal.view.InputBindResult$1.createFromParcel (InputBindResult.java:112)
com.android.internal.view.InputBindResult$1.createFromParcel (InputBindResult.java:111)
com.android.internal.view.IInputMethodManager$Stub$Proxy.startInputOrWindowGainedFocus (IInputMethodManager.java:849)
android.view.inputmethod.InputMethodManager.startInputInner (InputMethodManager.java:1726)
android.view.inputmethod.InputMethodManager.restartInput (InputMethodManager.java:1576)
android.widget.TextView.setText (TextView.java:4971)
android.widget.TextView.setText (TextView.java:4908)
android.widget.EditText.setText (EditText.java:110)
android.widget.TextView.setText (TextView.java:4883)
android.widget.TextView.setTransformationMethod (TextView.java:2316)
com.google.android.material.textfield.PasswordToggleEndIconDelegate$4.onClick (PasswordToggleEndIconDelegate.java:101)
android.view.View.performClick (View.java:6205)
android.view.View$PerformClick.run (View.java:23653)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6682)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)

* Sample Devices where the above crash occurred :

Brand:samsung
Model:Galaxy S6 Edge
Orientation: Portrait
RAM free: 235.21 MB
Disk free: 204.7 MB
Version:7.0
Orientation: Portrait
Rooted:No

_____________________________________________________________
# Crash 3 : -
Fatal Exception: java.util.concurrent.RejectedExecutionException
Task java.util.concurrent.FutureTask@81ad1f5 rejected from p.a.b.a.b.f.d@7e23b8a[Terminated, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution (ThreadPoolExecutor.java:2086)
java.util.concurrent.ThreadPoolExecutor.reject (ThreadPoolExecutor.java:848)
java.util.concurrent.ThreadPoolExecutor.execute (ThreadPoolExecutor.java:1394)
java.util.concurrent.AbstractExecutorService.submit (AbstractExecutorService.java:118)
a.a.b.a.b.d.c.a (c.java:1)
a.a.b.a.b.d.a.a (a.java:21)
a.a.b.a.b.b.a (b.java:5)
a.a.b.a.b.e.a.a (a.java:19)
a.a.b.a.c.e.a$c.invokeSuspend (a.java:6)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
a.a.a.o0.run (o0.java:28)
a.a.a.c2.a$a.run (a.java:590)

* Sample Devices where the above crash occurred :
Brand:Xiaomi
Model:Redmi Note 9S
Orientation: Portrait
RAM free: 2.22 GB
Disk free: 77.92 GB
Version:11
Orientation: Portrait
Rooted:No

Brand:HMD Global
Model:Nokia 6
Orientation: Portrait
RAM free: 1.53 GB
Disk free: 6.77 GB
Version:9
Orientation: Portrait
Rooted:No

Brand:samsung
Model:Galaxy J3(2016)
Orientation: Portrait
RAM free: 479.44 MB
Disk free: 1.07 GB
Operating System
Version:5.1.1
Orientation: Portrait
Rooted:No

_____________________________________________________________
# Crash 4 : -
Fatal Exception: java.util.concurrent.RejectedExecutionException
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@8206693 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@dbea6d0[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution (ThreadPoolExecutor.java:2086)
java.util.concurrent.ThreadPoolExecutor.reject (ThreadPoolExecutor.java:848)
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute (ScheduledThreadPoolExecutor.java:334)
java.util.concurrent.ScheduledThreadPoolExecutor.schedule (ScheduledThreadPoolExecutor.java:562)
a.a.b.a.b.d.c.a (c.java:4)
a.a.b.a.b.d.a.a (a.java:21)
a.a.b.a.b.b.a (b.java:5)
a.a.b.a.b.e.a.a (a.java:19)
a.a.b.a.c.e.a$c.invokeSuspend (a.java:6)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
a.a.a.o0.run (o0.java:28)
a.a.a.c2.a$a.run (a.java:590)

* Sample Devices where the above crash occurred :
Brand:INFINIX MOBILITY LIMITED
Model:S5 Pro
Orientation: Portrait
RAM free: 1.72 GB
Disk free: 87.44 GB
Version:10
Orientation: Portrait
Rooted:No

Brand:samsung
Model:Galaxy A30s
Orientation: Portrait
RAM free: 1.06 GB
Disk free: 38.82 GB
Version:10
Orientation: Portrait
Rooted:No

_____________________________________________________________
# Crash 5 : -
Fatal Exception: java.lang.InternalError
Thread starting during runtime shutdown
java.lang.Thread.nativeCreate (Thread.java)
java.lang.Thread.start (Thread.java:883)
java.util.concurrent.ThreadPoolExecutor.addWorker (ThreadPoolExecutor.java:975)
java.util.concurrent.ThreadPoolExecutor.processWorkerExit (ThreadPoolExecutor.java:1043)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1185)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:919)

* Sample Devices where the above crash occurred :
Brand:Xiaomi
Model:Redmi Note 9
Orientation: Portrait
RAM free: 1.46 GB
Disk free: 46.59 GB
Version:10
Orientation: Portrait
Rooted:No

Brand:samsung
Model:Galaxy Note9
Orientation: Portrait
RAM free: 1.74 GB
Disk free: 39.8 GB
Operating System
Version:10
Orientation: Portrait
Rooted:No

Brand:HMD Global
Model:Nokia 5.1 Plus
Orientation: Portrait
RAM free: 926.15 MB
Disk free: 1.16 GB
Version:10
Orientation: Portrait
Rooted:No

Brand:vivo
Model:vivo 1938
Orientation: Portrait
RAM free: 830.16 MB
Disk free: 11.71 GB
Version:10
Orientation: Portrait
Rooted:No

I have only started to see these issues after adding the SmartLook SDK so I am kind of pretty sure it is due to SmartLook.also, many of the above errors occur immediately after the app starts which I think immediately after the Smartlook initialization is done and SmartLook starts to do it's Job.

**Comment by SenNeonoveNoci** [comment]
Hello @mohdFathi thanks for the report, we gonna work on these and keep you updated.

**Comment by SenNeonoveNoci** [comment]
Hello, @mohdFathi all our issues should be fixed in the newest SDK version `1.8.4-native`. 
[documentation](https://docs.smartlook.com/docs/sdk/android?platform=android)
