### ISSUE TITLE
Multiple crashes in production with java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by TheFaithOne** [smartlook/smartlook-mobile-issue-tracker#99]
**Platform**
Android

**Technology**
Native

**Build instructions [optional]**

**Rendering [optional]**

**Affected devices [optional]**
Xiaomi, Samsung, Huawei, RED

**Smartlook SDK version**
1.8.3-native

**Summary**
There're a lot of crashes (mostly on background) that are being recorded by our firebase crashlytics and I believe it's because of smarlook uploading data because said release contained no changes other than added smarlook recording and this is the first time this error appears. Could you please take a look and make sure you're not overflowing thread count or feeding new tasks to a disposed/canceled thread?

**Relevant logs and/or screenshots**
Stacktrace from crashlytics: 
Fatal Exception: java.util.concurrent.RejectedExecutionException
Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@fd21e49 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@727534e[Shutting down, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 0]
java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution (ThreadPoolExecutor.java:2086)
java.util.concurrent.ThreadPoolExecutor.reject (ThreadPoolExecutor.java:848)
java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute (ScheduledThreadPoolExecutor.java:334)
java.util.concurrent.ScheduledThreadPoolExecutor.schedule (ScheduledThreadPoolExecutor.java:562)
a.a.b.a.b.d.c.a (c.java:4)
a.a.b.a.b.d.a.a (a.java:21)
a.a.b.a.b.b.a (b.java:5)
a.a.b.a.b.e.a.a (a.java:19)
a.a.b.a.c.e.a$c.invokeSuspend (a.java:6)
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith (BaseContinuationImpl.java:33)
a.a.a.o0.run (o0.java:28)
a.a.a.c2.a$a.run (a.java:590)

**Comment by SenNeonoveNoci** [comment]
Hello @TheFaithOne,

this is fixed in the newest SDK version:
```
implementation 'com.smartlook.recording:app:1.8.5-native'
```

Please update the SDK.
